apiVersion: v1
kind: Service
metadata:
  name: postgres-pgweb
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: postgres-pgweb
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
