---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: default
spec:
  encryptedData:
    PGWEB_AUTH_PASS: AgBFU3e0pxvo3RAYIx+DLq7MtoiU4XTPJv7o3NKqbyKegspg6WtKQ5Alaus4m3cacPa3TbsjUJDpgLT2eCL0iQqhjMfcRZN1nE0icE9pPV9W/fK8f0Fabe1ky1eBvfcIa1kS6hMx1FCp+CRqeCPt1sG/oF0vZe3aYs908IQMuaA4nrw6S8nVMH5xDbPfuFm5Bbphv3yRK75pn/B2WZgQULHUOp6e0+tAyOBALzwznAXVh7B12/0T3EZji7yc3uBxAZxf2uGyuB4TJOD4XLLi0hUJI2DtY7Xk+D0K9fPaqQZh1DyUmYbc75mEakW2pH5fjjawNIeiniFiW+v4yvoMWkfE+qdxr0rqDmBkIUXe4NdHqPdQQQ6M/8kqrMIYSGRwNgxf+GxOAcUV+gQ7moK/qLk8sj+86HsuVkYTy1cOCMuaTtyF7hyjBS/AIDPckXdqQS9sWfq3CXVpnxikQJVd/fTPPT1OPdK23VKnWs2O5cVHD3hnCn778aF6qXjO8aO3vHp0cWP/6JmZqC0Hwlsjv8udY3W1uD30FuccVBmhouPbqXosghKHO3h+a7oD1PeuGuNuv6lmb+wsfokeY5Z5Zy1KCmQpqFlOwfQ+4wdsG/2Rj7P7Yf61LNhW0MPdQ4WQbYUBWZDv0Ps+ycY6qd+6vr7P098MRhxs7+dxYdxVmye5P6Jnmvu9R/ceKO3WKy/fuJr9FWCs/fIqTWhgMIpltJ9EWrxIUb/NYD+vUz3930YQzmp5sneCCZwpaEHGtObgFm8=
    POSTGRES_PASSWORD: AgA6jZ96b6shSZjRQNriC1P2BxRbr9ysTo4ZE/Sm5sm7l4+vzZYTwOiXAjim3d0amXpB7upBpMUes513yhRUg9N3+sh0OWcBv0QnKis82XtsyrAKaR3r5X7GsAUxmZ49BYCaZjivVm0XHzo4rikwWPf4pfRAYfrX+dN/GMIUSBS5y2z6i4wBkRnHw/+7eZ0moQq0wa5wpp4qpYM4kqq/ryD7/cG90jhL8r6RwnXtrlFEpUqHjojeytq+ghHOj6U+d8ko6lJ1mdC52FNeHcYUZ28jx2c2HXY9nzAthIeFwmRUZwLVu1ueUrWNavyqKNEIy9AkBAI21kdqpeOFXXy9y9OS5X2UnJjx9fiX1lm/RC0GfGCco576mL0QKtHAEWRtRvWbloYjBTJJ6jH4CQI9ppZxByEori9FMMntfaGro7SeaX2Vg840jjEjctZ82sB+SkcDWLFFiZSV4LywxlDETGtlHOe5HhmR/CA138HkWY/NCL1OliR5xf1j7uC6QPl0kR72nJl5r6zeF83zZ5uZZaNxDMsyiPoG6DoO9nIe8pc2IcEPqGGnNeA5efdRJFTISXLw1pawbBGmCu/2qjjm3n4/zpPb3SIuhVXWqZFZ3BbVA4SO5PuyzcfOreOIroaGclxnoQxk4Pj1RMK81P1CDJet5gvqI/cVHTt10wcXKsYkQwKygXjVyryhHkA/hWoGJaDTTj4uvHO2YLrJvBM5sg9jEAV2sat+mMB+z4iMDGuE80RvunifSLRnCfU6ml7C23I=
  template:
    metadata:
      name: postgres
      namespace: default
