apiVersion: v1
kind: Service
metadata:
  name: mermaid-live-editor
  namespace: mermaid-live-editor
spec:
  type: ClusterIP
  selector:
    app: mermaid-live-editor
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
