apiVersion: v1
kind: Service
metadata:
  name: verdaccio
  namespace: verdaccio
spec:
  type: ClusterIP
  selector:
    app: verdaccio
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
