apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - broker.service.yaml
  - gotenberg.service.yaml
  - tika.service.yaml
  - webserver.service.yaml
  - webserver.deployment.yaml
  - broker.deployment.yaml
  - gotenberg.deployment.yaml
  - tika.deployment.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml