apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: ssh://git@forgejo.biplane.casa:2222/artemiy/homelab.git
      targetRevision: main
      path: clusters/casa/apps/home-assistant/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
