# База кластера zitadel-db.
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zitadel
  namespace: zitadel
spec:
  cluster:
    name: zitadel-db
  name: zitadel
  owner: zitadel
  encoding: UTF8
  databaseReclaimPolicy: retain
