apiVersion: v1
kind: Service
metadata:
  name: sure
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: sure
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
