apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  vaultAuthRef: vso-rustfs
  mount: kv
  type: kv-v2
  path: rustfs/credentials
  refreshAfter: 1h
  destination:
    name: rustfs-credentials
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
