apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-mailserver
  namespace: mailserver
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-mailserver
  namespace: mailserver
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: mailserver
    serviceAccount: vso-mailserver
