apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mailserver-admin
  namespace: mailserver
spec:
  vaultAuthRef: vso-mailserver
  mount: kv
  type: kv-v2
  path: mailserver/admin
  refreshAfter: 1h
  destination:
    name: mailserver-admin
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mailserver-metrics
  namespace: mailserver
spec:
  vaultAuthRef: vso-mailserver
  mount: kv
  type: kv-v2
  path: mailserver/@monitoring/stalwart-metrics-password
  refreshAfter: 1h
  destination:
    name: mailserver-metrics
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
