apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - namespace.yaml
  - merge-message.configmap.yaml
  - runner-dind.configmap.yaml
  - runner.configmap.yaml
  - runner.deployment.yaml
  - runner.pvc.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml