---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: default
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgB0Vw+GPF+fqRNuPvicBNLIH34BfA4scfBBlAqmrK83stsTfXakkLxcL3jgp/sZbt9LK53j8IFOrF2LvEqMpStw3SbmhopsoWWO3u2I0Xmr1t7cx58+OHiWSsnIBoS56k2xc2aJ4yWe+ME3wTQKJ/AKZu0rV6a7oPrKFKK6T31gYFUhWDUuvp3Ai7fK6g+SMwybz2+uVYn+bThWurloQX5t8kpL6opDcGay7eNBcfIwikYv5IhVRBgfgMwKSrJ6+Rt85cB1tewx7aFbIF0oDkAcbiG91H6CLyJTTlMQjMhbm/oLSjyHMCy4BnDLPeo2FS2rmfTP8Ygp5P6hhQt7WV9sCNflc1YdMOq4dEogFThhDKa4oY5X+6CZfEinCKPth186UlF7SpMqyV8fjo7Z4fX/HNFGx+IvLKHt3Z54QUKRwwkCLPVPD0rOcF19k1u2H63l8DA0T803XyaTng0W/y64SY8rEExzHY5g9QQ0gOMsMXfPmtFTIOtd/zJkllF278rogG8ORV4wN9ICRWPwroMsCkuT4AT4l+70jdWxgXCcz5dvWlO8JCkuJsurOSzyaseglZqRr8k9EzWU494MitW6ygjmymsgrhh2VmEzlz7xnQ4XbRqXa/zE078AWfDtYjIm7MXn4gnS7RAlbi2GaN5lrPQ3E0QhSSiydBFOxCJTLekhE1Nxo5xy8dtWzQbsypZvzkMGbYddZeRmaVC/7ghnXXmCYXjTVZ4y4KiLP00ucg==
  template:
    metadata:
      name: grafana
      namespace: default
