apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-alerting
  namespace: monitoring
spec:
  template:
    metadata:
      name: grafana-alerting
      namespace: monitoring
    type: Opaque
  encryptedData:
    NTFY_TOPIC: AgA+imIzCoGaFI4G2x6MT+I823mK8060Q11cMoyTn4eUC2Ozlxu29/t/h/qSyMA96JjZsj5ja+eIKvCT5J5KByjxmZuDyZJCs2R6Wf/fFnnqdCmtypRH62utSCIwawdzL4BEQxtXwJub3KrwVKrAY4CTXpG27xWX8G7TBjumROqw0mzyzIUuEerX9jB0KrBjYHGXkvze7ukWfvgmPd2ztbpKk6cS5XjcateF3lyX0H9PsP88InL531VWhmZyIT9r1nL520uvKPk0jtI2bUt3yF57KdgoGIYM7FPjBZe0mYEfc6OgTUISSDcAhFlF5WgSiytoMO06sI7QmTFKm99KHOcTuuIEzq0UGt+gp34SDHyvi3ceQZPjb/pzuSy6Oh4XyNngLLB4xFd+2sewcZPnlQLiGVjfyCeL3boZEY97gR7Q+bNqLZRAJAheG3CzHTft0MyC8VNhD9PQtmLFGUHz/Y1H0a6vCz20dOuzjCkGOFziJEiZcgBONsEQbqngnfVhWLP61TyEQ/TPw/u/qrVHMn0QVmyDb5q/+RRi0o3MmSt37FKrnM7IoRNSAIVK7Mr8lfFQ5H4EoX84O5eOhckFeOBhvA5WCm82/KMFcd68b8Bg3RH5SVROOHGU1DL6fba/LBaPJhB4m6eNc7EYqLsaRH/XMqnq3wu0HchDxrVPeDyn0p4vhrVQm7GMPTvvb8DqB/Rd1e3oTEsZDdlN1oXHFvKAqMxucNtcT1ZCpcW1b4k=
