apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-grafana
  namespace: monitoring
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-grafana
  namespace: monitoring
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: grafana
    serviceAccount: vso-grafana
