apiVersion: v1
kind: Service
metadata:
  name: glitchtip-valkey
  namespace: glitchtip
spec:
  type: ClusterIP
  selector:
    app: glitchtip-valkey
  ports:
    - name: valkey
      protocol: TCP
      port: 6379
      targetPort: 6379
