apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-valkey
  namespace: glitchtip
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
