services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z,ro
      - /storage/apps/caddy/data:/data:Z
      - /storage/apps/caddy/config:/config:Z
    networks:
      - caddy-net

networks:
  caddy-net:
    driver: bridge
