apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: technitium
resources:
  - homelab-config.yaml
  - technitium-dns.service.yaml
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - pvcs.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml