apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: technitium-admin
  namespace: technitium
spec:
  vaultAuthRef: vso-technitium
  mount: kv
  type: kv-v2
  path: technitium/admin
  refreshAfter: 1h
  destination:
    name: technitium-admin
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: technitium-metrics
  namespace: technitium
spec:
  vaultAuthRef: vso-technitium
  mount: kv
  type: kv-v2
  path: technitium/@monitoring/technitium-metrics-token
  refreshAfter: 1h
  destination:
    name: technitium-metrics
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
