apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-home-assistant
  namespace: home-assistant
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-home-assistant
  namespace: home-assistant
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: home-assistant
    serviceAccount: vso-home-assistant
