listening-port=ref+envsubst://$TURN_PORT
listening-ip=0.0.0.0
relay-ip=192.0.2.10
external-ip=192.0.2.10

realm=ref+envsubst://$TURN_REALM
use-auth-secret
static-auth-secret=ref+envsubst://$TURN_SECRET

user=ref+envsubst://$TURN_USER+:ref+envsubst://$TURN_PASSWORD+

log-file=stdout
verbose

no-multicast-peers
no-cli
no-tls
no-tlsv1
no-tlsv1_1

proc-quota=20
total-quota=100
stale-nonce=600
max-bps=0

min-port=ref+envsubst://$TURN_RELAY_MIN_PORT
max-port=ref+envsubst://$TURN_RELAY_MAX_PORT
