apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-beszel
  namespace: beszel
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-beszel
  namespace: beszel
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: beszel
    serviceAccount: vso-beszel
