apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ats-purge-token
  namespace: ats
spec:
  vaultAuthRef: vso-ats
  mount: kv
  type: kv-v2
  path: ats/purge-token
  refreshAfter: 1h
  destination:
    name: ats-purge-token
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
