apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: local-ai-api-key
  namespace: local-ai
spec:
  vaultAuthRef: vso-local-ai
  mount: kv
  type: kv-v2
  path: local-ai/api-key
  refreshAfter: 1h
  destination:
    name: local-ai-api-key
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
