apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-playground
  namespace: postgres
spec:
  vaultAuthRef: vso-postgres
  mount: kv
  type: kv-v2
  path: postgres/playground
  refreshAfter: 1h
  destination:
    name: postgres-playground
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-pgweb
  namespace: postgres
spec:
  vaultAuthRef: vso-postgres
  mount: kv
  type: kv-v2
  path: postgres/pgweb
  refreshAfter: 1h
  destination:
    name: postgres-pgweb
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
