apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-seafile
  namespace: seafile
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-seafile
  namespace: seafile
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: seafile
    serviceAccount: vso-seafile
