apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - k8s/namespace.yaml
  - k8s/service.yaml
  - k8s/deployment.yaml
  - k8s/secure-headers.middleware.yaml
  - k8s/networkpolicy.yaml
  - k8s/route.yaml
  - k8s/vaultauth.yaml
  - k8s/vaultstaticsecret.yaml