apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - service.yaml
  - exporter.service.yaml
  - deployment.yaml
  - exporter.deployment.yaml
  - config.pvc.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml