apiVersion: batch/v1
kind: CronJob
metadata:
  name: uptime-kuma-sync
  namespace: uptime-kuma
spec:
  schedule: "0 0 1 1 *"
  concurrencyPolicy: Forbid
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: uptime-kuma-sync
        spec:
          restartPolicy: Never
          initContainers:
            - name: install-deps
              image: "oven/bun:1"
              command: ["bun", "add", "socket.io-client@4"]
              workingDir: /opt/deps
              volumeMounts:
                - name: deps
                  mountPath: /opt/deps
              securityContext:
                capabilities:
                  drop: ["ALL"]
                allowPrivilegeEscalation: false
                runAsGroup: 1000
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
          containers:
            - name: sync
              image: "oven/bun:1"
              command: ["bun", "run", "/app/sync-monitors.ts"]
              envFrom:
                - configMapRef:
                    name: homelab-config
                - secretRef:
                    name: uptime-kuma-sync
              env:
                - name: HOME
                  value: /tmp
                - name: NODE_PATH
                  value: /opt/deps/node_modules
                - name: UPTIME_KUMA_URL
                  value: "http://uptime-kuma"
                - name: UPTIME_KUMA_MONITORS_FILE
                  value: "/app/monitors.yaml"
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              volumeMounts:
                - name: config
                  readOnly: true
                  mountPath: /app
                - name: deps
                  mountPath: /opt/deps
              securityContext:
                capabilities:
                  drop: ["ALL"]
                allowPrivilegeEscalation: false
                runAsGroup: 1000
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
          volumes:
            - name: config
              configMap:
                name: uptime-kuma-sync-files
            - name: deps
              emptyDir: {}
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
