---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-sync
  namespace: uptime-kuma
spec:
  template:
    metadata:
      name: uptime-kuma-sync
      namespace: uptime-kuma
    type: Opaque
  encryptedData:
    UPTIME_KUMA_PASSWORD: AgAQsXsMxLh7axa0HBU9TLq9GpjICvqnA8z1BbGMVY6w3xhK5J0lTo1xhqCHCveWAcHnXhnzblwqmp4ivgcv2Ua1j02vP0QoAoUi9x4x6IAUk5HwLZYBo2AxQWk010K3VXBR3bLqXGZfhkviwjCyVRt4Y5wMTMXHDidn76WfNayARNyHUh442jrLw8CjIqaTC8FYk/IElpV0i7qYZnSjbaWjb/Vu/jy0huCmRu6/FD4pfzBren924ccwfcJCQdsu/8rCjA66zmoVKfBwaIZf9cixVZR42wfKcu5toffuaZ9UYm+rwhUwavD9KeZXwfeHG2dwoNIRD9mtaz0ZySx9ozyG7SGHb7n0dqNScltnde/NvCZ1bEWV5zr5u4b0dHRpfoIOAK2JfLwTWS35RnzLP2NmokYczgjfp4dLoq6+7S5dPdT5nlzfxvFySABGmAbvs6ku8Th06IzmtgKOiwolq7d8S1wFyY0XCsc2kv6oCmFhxcdkLMBZUDITvxXPjXsfKVU+LtNH8bc4ivWw97gfs86p/zN00wxj10FK7IA/XUszXT3T4lzmU/l2u0aDTHxixI6OYRJ6Fs6Ae5GSKrShxPrAeqt8HlyBiVGo19ptC2Uyfi4E8uBVXJNN5GV9QJFp2vdXxgRBRThLPJPXXnaMINYckxKSrZU+8jh72Uu/bscnGYkelKvGzPyQOMCC3k2GmxRDbT5qO31gvnP48dsqhsUC5Lq8MyK1+W8=
    UPTIME_KUMA_USERNAME: AgAG4dwWX0YtdPX2tFPIuWIVwnrR1wCcJNLZ436BNr0AJkI4t4DO4L9xB/XtOcZCr+Gv0wggI4tnFygcv/1NseAiIfbFRtfYpLeMQtJhsI7WMwUHF7XcQnRcMMh/w7WqvzllQ1EYapJzxzjHGIA+hAnDYR5dsX8je5/CMFZo/qzDlu7HmY7zmNCE5ZnqyltVZGlIpUueqUvB07FF9ID/cZg+v3l+UeyUW/K8dyFonlgKh0LrRDpFsQX/C2t9lTMnNa8JWXI3PFrvp+KVw/QAwIDA/tVX2OqspL22YcVB1z8gmFoyM6TuwCS34asZ0jX/PkSyGKLYP3Y8RdRcSp50TOkNwNCKsmJiDN/6cSA9p5Jp55vdQVg8y4u7h4uLMANbyNTuPpgWok6tc/WzgtLG2q6e3VO0avgY5HaRNJbQ1aVcTE9AMy/6jHv0LDgP7Gig6Dpn084FlPLPoVYMkezx3R4VRNEuNq6iydL3XWFvBnD+56QwC5tfMq5CXIYDFJeZqPH7vJvD7wRhM+Y/btFZn53fP5nz/cA8iGK8GajUcLQ9VwN6GhHwHNcMAw3mK77pNP7A3BIHOxiPU6BO3Nby3USi6Gw1g5lDsjscJPwmXb2/DjJJUP5CCdJ355NhCCfy9DRA3RkG0KjnkjqlEH/8YFD1e28L5WSGvk/kekjEVMwqbZB4fXe+VUsw0tVIw3aK4P85pQN9yg==
