apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-technitium
  namespace: technitium
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-technitium
  namespace: technitium
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: technitium
    serviceAccount: vso-technitium
