name: gatus

services:
  gatus:
    image: ghcr.io/twin/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    container_name: gatus
    volumes:
      - ./config:/config:Z,ro
      - ${APPS_STORAGE_PATH:-/storage/apps}/gatus/data:/data:Z

    environment:
      DOMAIN: ${DOMAIN:?set in gatus/.env}
      SERVER_IP: ${SERVER_IP:?set in gatus/.env}
      NTFY_TOPIC: ${NTFY_TOPIC:?set in gatus/.env}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?set in gatus/.env}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:?set in gatus/.env}
      TELEGRAM_PROXY_URL: http://${SERVER_IP}:8440

    networks:
      - traefiknet
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.gatus.rule=Host(`uptime.${DOMAIN}`)
      - traefik.http.routers.gatus.entrypoints=websecure
      - traefik.http.services.gatus.loadbalancer.server.port=8080
      - traefik.docker.network=traefiknet
    user: "1000:1000"

    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

networks:
  traefiknet:
    external: true
