---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: victoria-metrics
  namespace: default
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgBmhGgJDe7+j8xFQ4X0Ekj2It5Nuv/XmzRl7cSpeH5C5JtHAtGULpWGwLDLaKHA0TVxAFx6OIo8S/skKXrElhOxZ7SMSyP0t/L2VaBOCloXajDDOyRxac9ZIxOk+4N8HRCvlucemlgT7Q21hO+8PK66c7SNn8RiS+NzTUCsRIAEGdJWa5XJiM2F0jMbAFbKAPq2Us6amjwLJqxmkv/KCVPIWX7gWKp0sPyr5DPw3ZWexFGE7GruSEpCMiMVSD5Zwhv1zTT8Vcnu+Q8I5GVoUPLkYo1AqEGNR2qjSnJnJ9SSJxFWDhTvUZtUO1osUGabY5jHHeEKaSTeaA1m6JcfqtFwFZwSolAh9M5Rm8EBqADCmSHcR5PqPqMncH9ls4BHjvv9ZrqG41Qzo0QQwk3wVN+F/w5STZ6LeLKIeMyhJl8KHN6g1W1myU2Ls9TeYV1hQGflNOJgSwOBKNrsmlr5AopqMFhVSfZr+NdvdCCLuXzpuJzs4f8pc//RGx3K0Y+ake+/23D4oBjP6yabFUeGgTDCNMUKf1udNGDO2YmD0Cxn/s4Z5zue+S91xue1cabxHTuw5mGews82iUyosym5syoaShL2Ew094HGfST53xnpmIMcWCAMLC4IY9NBB9X2h78MiuXZtNBtAT21Glmz926nu3UQoG/HukRBfbnm3tPhT5Afw/vECjJLWb1nvSV6TMTj5pw5LzTGmiXd8VRi6QE0Bf9FT6osdFbxlfki0q9j6lA==
  template:
    metadata:
      name: victoria-metrics
      namespace: default
