---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vmagent
  namespace: default
spec:
  encryptedData:
    UPTIME_KUMA_METRICS_API_KEY: AgAstUck0sqi4ZWSp86bxD+3THJcthmSlPZwUyUDlVSFsXs5e33Y8Vy5/h6dIa34dUd8R0kmnwrYnH4AIffnjPPW9tuCcRWBH/Ly2NE/WbOdgxE8LY7byFrWquJE1Ds3SedOMaGSz1/N0SnBi5/VzRosymkn3co/+X+abrC9nneRxV66pLy8AxAkbwI3Z4HpSAEZWKYf7AAOBwa5Amd5NZAFd1+JqZwr0laddgIgFqtB3HFGfnVEeiZbQ9MlmCvcEwjddlJa0HMHNrd6kMgChBjBf7RfXGllbOF/KnKi4hBeAZzuTJ0gb3cM4htbwLl3yJpy6bWF8xSTnhwpOOACnmRdfTm6ftVHAJ0SrZAn1QzREZqY3/N7jChMxPlyi0ByhoCsLxM9FSPZf/knx4PvalhBq9zI/x/X4edtG6A73Io0CAg3fYsd6QXMNVYpmzhJtQxisse8hF6uF7XwHlAH8Pn95lPGVaQ8a70gOxMbX4ddRnOfNPU6jF2TRPSsa44UFBLif5Sssavtwgi0cRL8mJ/X566k3WiTyOUUtC8jFX8xJ2N1shGC7TI99kanDlOS4aTxyHgT0oMUBY229ijjLqnyBhCXmfSmXz2a9z8t771iJprup1JZWZ/YL42tpaZ9JimxFYPvwZniMCzip4qHNCCetpFWVk+dT83hpUJxlz2N5+Gy+ygdU45sFbMmdtfsipdNA2u8EOPyXPlx3eL2/29RwpdzWWCZ0KrifdFNcZiojwVFgjPglw+EkDNMDA==
  template:
    metadata:
      name: vmagent
      namespace: default
