apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vmagent-uptime-kuma
  namespace: monitoring
spec:
  vaultAuthRef: vso-vmagent
  mount: kv
  type: kv-v2
  path: uptime-kuma/x/monitoring/uptime-kuma-metrics-api-key
  refreshAfter: 1h
  destination:
    name: vmagent-vault
    create: true
  hmacSecretData: true
