apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-vmdata
  namespace: monitoring
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
