apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - k8s/namespace.yaml
  - k8s/broker.service.yaml
  - k8s/gotenberg.service.yaml
  - k8s/tika.service.yaml
  - k8s/webserver.service.yaml
  - k8s/webserver.deployment.yaml
  - k8s/broker.deployment.yaml
  - k8s/gotenberg.deployment.yaml
  - k8s/tika.deployment.yaml
  - k8s/pvc.yaml
  - k8s/networkpolicy.yaml
  - k8s/route.yaml
  - k8s/vaultauth.yaml
  - k8s/vaultstaticsecret.yaml