---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ats
  namespace: ats
spec:
  template:
    metadata:
      name: ats
      namespace: ats
  encryptedData:
    ATS_PURGE_TOKEN: AgCKQfnhtr99K1s3MMWw6ptF/cFDCcszMDDL9bWywrSDlYStQPc5grgjdTdDVRfO13yAJ83JBMchJfEH/gAfH6zMxktnK3FnRcfykVLM2I2cIIlyRkVonxaYpwkfqi5MhA5udKC381SoTNNNsY6W6UG/PtoR/OTzWGyCvX6PO/GE/aXVKHm7SGnlbtNsHcZX+JJBMf8nMX57xDbp2rXHRXhBuWP5xCUGxanBY0upiy8DQLi7DbHzGv8VAIkO2tmXcGQ25zfNZC6V6ZZTq6P/fxKGzb6eSHssQYQBjPB7rXEndswDB6ZfD6QEitSGzSCpkl/qus4j8bgW5Lhto0pzKDB3qTkLjDqT8i6ZVnD2QHhhy0HwmmUDJYAejFDJw3GPwBzvUdautV+cEx0oeZlCMCBwoT5sIHQFyq7D5fvKCvCWTCCkKsIFoDccxdYbngNFiedBpJTv9OaFjInvRee+eo3raCCwhOd2IMWPnSkixUd0DZDc0JI6To+PXlESy15lMQ1qATVJOk+GhE1+p9gVe4W0e1ndbhlo+W8iMcO9kw6ezFwUDrzYPikv4JihvGqekrd/kL/r3M2E37tSVhv1Sn18LpyiK8lBSUIPIU6RxzvywrRAYtgGAdBGMjaKccnQ/0JJbkl6Raj5+kQ22eDbnZWWX0x50dvyVWKOIJD6SnZyVt7JlhIKQmyjgXgFQP70zVsJhlykvZQbdp7Tku06HhaVzSSIWbfJbMzMk85TXzMMXOAXSR2xI9ARXTdmgg+9eT4=
