apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-ats
  namespace: ats
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-ats
  namespace: ats
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: ats
    serviceAccount: vso-ats
