apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lute-data
  namespace: lute
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lute-backup
  namespace: lute
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
