---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: local-ai
  namespace: local-ai
spec:
  encryptedData:
    LOCALAI_API_KEY: AgCRt8bwBB2Q0dC0ASlTaTBCR9b/9zPuHzQMz4Q7bLcgRCIKg54eprfToI1Ix+IKBpZsvcfyFaPZmaujqPt82o9JdQxzFrwOx75wsfzT25ureaVzY7PHc6U4m/8+6QMlUvgDMJBatquIfZ87Y6b+SEE5cOHCFTylB8a+cvramwVwiP0SNlJ/DnIkfGAnHGJMsrvrqGKI9CJK8h/HLM/ayu2Qk/FZ7yoVpYfTunBvuPE8CCKADJFAn4NQrYwQ7U+7k9IZPxQWrM1+uDQ5npsU4+14d41VpMBYFUdl03Y0W59i2/ynX4wRgsO7QEeNsm1MEbpaUYO5mEPCOh7FQT3nEoDG2HwzmlXtIVt7j5YHSzccQFTU9WlUSdRxQpcPpnK/ozMcrRHatf6QySY2mN6tTNg70IMe/FWiPAJAbuhuPj9g6awdew+G16VsfzyyW9CY6dJ32Yf37UEVPYjGgq+qNrh3G8nNyQGP5UuTx5wUSbppzkURhOqHoj9Uu2jEU16NjUE7Tma7jK82kgioHL5NFh0nnqgxjK0ycfwECctCFR0CgOhYkRv4PBgkZocGzkCRlX/tQBTO2i4uewEHXbbZTyMuqhbCBiQwOfZFgMlUKBOPlyQ+aeHlu0xnHesGsr62hPmLVOxwIYX/qLqO2Lx7KN/KY8IjF4urV/2tkdogASDYTw7L8OrwCvukbLCsP6xQVMYg6ZPjIpgIdNiP/4+rNvLinDN42qJ8dKItDEDus3sFqiUQzmOGHIPtauQZIxg+urvAcf7JVNW4V5iJYQGzSB9S
  template:
    metadata:
      name: local-ai
      namespace: local-ai
    type: Opaque
