apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-db
  namespace: seafile
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: seafile-db
  template:
    metadata:
      labels:
        app: seafile-db
    spec:
      containers:
        - name: mariadb
          image: "mariadb:10.11@sha256:8020e05c4c498d06c87f0a1db010eb79bd6f8fb30e9b763d4690c34ce1e61008"
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MARIADB_INITDB_SKIP_TZINFO
              value: "1"
          startupProbe:
            exec:
              command: ["/bin/sh", "-c", "mariadb-admin ping -h127.0.0.1 -uroot -p\"$MARIADB_ROOT_PASSWORD\" --silent"]
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "mariadb-admin ping -h127.0.0.1 -uroot -p\"$MARIADB_ROOT_PASSWORD\" --silent"]
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "mariadb-admin ping -h127.0.0.1 -uroot -p\"$MARIADB_ROOT_PASSWORD\" --silent"]
            periodSeconds: 10
            timeoutSeconds: 5
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          hostPath:
            path: /storage/apps/seafile/mysql
            type: Directory
