apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-redis
  namespace: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile-redis
  template:
    metadata:
      labels:
        app: seafile-redis
    spec:
      containers:
        - name: valkey
          image: "valkey/valkey:9-alpine@sha256:ee91f7a174ac4d6a6b0685b3a60e321f0a9dbbb691f9b0e285be2ba1d1be8328"
          args: ["valkey-server", "--save", "", "--appendonly", "no"]
          ports:
            - name: redis
              containerPort: 6379
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          livenessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            periodSeconds: 10
          startupProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          securityContext:
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            seccompProfile:
              type: RuntimeDefault
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
