apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seafile-db
  namespace: seafile
spec:
  vaultAuthRef: vso-seafile
  mount: kv
  type: kv-v2
  path: seafile/db
  refreshAfter: 1h
  destination:
    name: seafile-db
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seafile-root
  namespace: seafile
spec:
  vaultAuthRef: vso-seafile
  mount: kv
  type: kv-v2
  path: seafile/root
  refreshAfter: 1h
  destination:
    name: seafile-root
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seafile-secrets
  namespace: seafile
spec:
  vaultAuthRef: vso-seafile
  mount: kv
  type: kv-v2
  path: seafile/secrets
  refreshAfter: 1h
  destination:
    name: seafile-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seafile-oidc
  namespace: seafile
spec:
  vaultAuthRef: vso-seafile
  mount: kv
  type: kv-v2
  path: seafile/oidc
  refreshAfter: 1h
  destination:
    name: seafile-oidc
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
