apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: structurizr
resources:
  - homelab-config.yaml
  - structurizr-properties.yaml
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - data.pvc.yaml
  - networkpolicy.yaml
  - secure-headers.middleware.yaml
  - ratelimit-default.middleware.yaml
  - oauth2-proxy.middleware.yaml
  - route.yaml