apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: beszel-agent
  namespace: beszel
spec:
  vaultAuthRef: vso-beszel
  mount: kv
  type: kv-v2
  path: beszel/agent
  refreshAfter: 1h
  destination:
    name: beszel-agent
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
