services:
  navidrome:
    image: deluan/navidrome:0.63.1
    container_name: navidrome
    user: "1000:1000"
    environment:
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      ND_SCANNER_SCHEDULE: "@every 1h"
      ND_ENABLESHARING: "false"
    volumes:
      - /storage/apps/navidrome/data:/data:Z
      - /storage/media/music:/music:z,ro
    networks:
      - traefiknet
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.rule=Host(`${NAVIDROME_HOST}`)
      - traefik.http.routers.navidrome.entrypoints=websecure
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
      - traefik.docker.network=traefiknet

networks:
  traefiknet:
    external: true
