# Логин/пароль админ-пользователя Forgejo (user) для чарта.
# Запечатан на сервере kubeseal'ом для namespace forgejo; пароль только в чате —
# после первого входа сменить в Settings → Account.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  encryptedData:
    password: AgBiphL54s1Gqzl0Kokqh2+NGfyH/fTAR2hp6ZeAUOcXI6W8wmUuU0dKN3mf+sLvcYQKJCsRhzvW2FCi5Pkp7gbOTavoNrQTwBZ+81XNSlBSgQh/cKVTDFaqWhu7X+IJlZEcz+sUhbbQhMKe0gVQOszwgRcGCYC65py1gGpqfXoYL8x4M8bp+/M/pGNnhGoFPzZ09FWJScSvcfbR0KqUj2uoyPS5abeN8svTaMrdHPE04QdR9YbmsflibtXnBKTckrb6g6tqYEePB9aA83v4S1xPGJxBeng7b3v0Ovko+tqqabXANG6TslrTheDG1zHC3h3aRmh2YpcFzCPBXV08vXEQx4XJr8D+PpfLItll+lm6cgIWL0bbWLmOngiBmw6mHVxqDlcBERFDrvVRuVAyxQZJNGpHYKVFGht7QDVUqKyNmUgQVGkSio0uEqEmmGeomlp84P0wS5Hm02Z+FJ90ZayuEcyWbD/TvoJPwLqFieZqQTT36wZfg71SCcl1lC/qUDnnMnInHO5SVa18doBv1LrZ+yo8N5LutAJeF5qeblMc8UDSfl2HXxcm26cAyYgVS4SYX1zlKqBQaVBkllnZwfZfCof5kWgSnj7C40TANgswhdFUYLDJqyriEMcDSs26/C9KXNWNEfxU0hwOZYuSPA8wGaaMZvyBAWO1yZaFnRk1HK9/x87kaW5YmpVGk3cxUtppEb1zaRbpVEbnBUolAlpSb0Krm/P0mrg=
    username: AgCcSZ0BeUTwPGq8vsZivNImZ4fjNx0mbAIMdFkpqm3gq9gQqB+tZOOSmwAltSKO4zOK67FNL/qB7jmvYtaR9vO4eHwRsHfKlYwaRo7NeBD9DdRcEeDS6hR20TlDE0MJxJ+HVsBKmpHUJ2zDxW+rgqjjtqXrBpQXQIYVDXXmy5R5J1Su2sSOFAoHaJ/629xCb6V3GaAAuhc0qG+LbYzPvnhCmILcPQZD97SLUwX8GhjK2Zd0ie/1t94B3VR0ex55MzDaYz0uXknuW3B85RT7mljQVV7p1V0piDIB21Y1TzPGpJKIGWwTOstfn5R7F8L68JneOiDx/c1fqZBoKXU5tni0dM/jBw3fFDB6X2dHUhqOT/R0ThNbQLBhx07xyfZ0m8zSu1hM5u0FfhuJDiK0hnhzuotErha1RWBuIB3jRvjB4r6eDeI+Am4shNkSEv0t3ACwySqIqILx3Lh2OpONzWGRzY7uIZEM6tlPg1TvFE6BCmNcV+mhU+HBVQ6C8sZ5Lkf1QTadGJD6+6yg4X620nXUz7JIGmGbX6lP9ezySMkAjUZsP11ERtHm+QEPcjtjnrv+7g8+W/H9gO1OHUxOI2pGBtG1qWG+GmcMrFBlMN0SqoXXqmBZWayyZAdfsSeH5FCfciPM6nGJkvjcs55Pokdmvg4Xf+RPLNHS6fsae29E9wuW7iiYHaYNQXt8xEO9E3fOity+3bD0R9IZ
  template:
    metadata:
      name: forgejo-admin
      namespace: forgejo
