apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-forgejo
  namespace: forgejo
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-forgejo
  namespace: forgejo
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: forgejo
    serviceAccount: vso-forgejo
