apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-exporter
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin-exporter
  template:
    metadata:
      labels:
        app: jellyfin-exporter
    spec:
      enableServiceLinks: false
      containers:
        - name: jellyfin-exporter
          image: "rebelcore/jellyfin-exporter:v1.5.2@sha256:8a1294b7fea80993e4ec18220e391578e0f9ca9e109294fd6a379d2cb5213c85"
          ports:
            - name: metrics
              containerPort: 9594
          env:
            - name: JELLYFIN_ADDRESS
              value: "http://jellyfin"
            - name: JELLYFIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jellyfin
                  key: JELLYFIN_API_KEY
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          securityContext:
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
  revisionHistoryLimit: 2
