---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin
  namespace: default
spec:
  encryptedData:
    JELLYFIN_API_KEY: AgBF0ox89nhlB8XLB941IZGVFmtWyS5/26EsXCuci2E/xmZryDdMOiZQVOq4mGtGDgwfv5OblbwFmPlSgZiv51IDEYMFkyn2+wcR5I/T0idFumc5Ut5Ixml8Tv96oz4TXBTpO2spe2o9omNwqaDv9Qy0ijY4bFbUhVmv+psfQH8D9jhwIquZAREosnwEnjPjWEtaz6t/VBAxBBJ005imJ1HYhYV2DZFsjFTLQD09xRstFgfobVYGstioh6a4w/aE+fBgARcrQJ70V8zdVw4Uhgb8faCLDo4PlOD1yT5G+7IbkdUEBTem7n2tyHP+S+HE2IBS3uBeRHas6tgxv8ZzVK7MNwSyzV7yi8RGPisy2gjs+hIQTWvowRPqJXYGkMgEuZZkCEyts1lCe87nFK3TwStBvr/HBjEioq6YtfHZvwEV6IbEYT7Ao6JJianIhYzq7XOYhNcZ4DETlOQnSW6xe7RXbrEvb/wjCweRPe8sDIAiBttIlg+31eme7gLTeXy5G4yCn2W0EyuQomsPWyEyE6VTnlGdDqsO/VKWph8LBlHjn5fzwBfX2Z3nbl+oEHc7NxNJ7x2tK3o/A5G2hD4XWqjeiDbdWrKcp1rAlDfTNPPkfe8Sduew1cOLuR/YEj0r94MNc5yegqORJuKia99pLfQDIciuFt9+ytwrBopjtwZ2rBU9aEsgazBCuUUtisGfdTB1/KGBUqWKpx55qwk13tEg9TndnoubKz/fLAVZoMYVWg==
  template:
    metadata:
      name: jellyfin
      namespace: default
