---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  template:
    metadata:
      name: jellyfin
      namespace: jellyfin
    type: Opaque
  encryptedData:
    JELLYFIN_API_KEY: AgAifudQ/epftIgwAXr8RQwXOUOQrBNskv9pQynzvKDuyFl5GbbRLTvNf88hJGP7LNZZoRpBSHXQTdRlxZfd4xVblxaVoomKjfbbkTpYNDvJD6RnzJWXTc4ai5zvZH48yjmBqrkNf0mIhaVFLqHuQmgLnpBwq1r/oq5PZpBR2HhYXlDMbpLjJJBB09w/z6kmTFTEFIeExAMnp04gWR9o/TejI3BnPsFG85sjGkFn9b7fzQ+TFay3y/q0PvsHR/Qu2MpHJ2STJGF7o29PS/A4oa+Afcyw+G0Ozf9e2qdQG3ctGOaWNZP5AjUuIedtS4YxqfigOeXxi++zgIKQk5SX7K+nXo+uyO33VgeI8fRTtl1Mtc2759Xjai01gJudC1Sun1cB3SkYB4GrY0TBIBqfULC48K1AbTEuw+mH7YLF9DkpLJgMV29sbIXA4gXLRT5W0zfGKiRNFT9JtLRUOpYhoiayq6k1hhrg0fp7X33t0MhKUeR1sN84EEB0VCdgCrx8p9WHCtP8bcbNVnR8EnTZflMsuvRQc+ILM3y+djbXdPF4iDE04oib2ZSN9+TR9FN2W4R1N30ArC0avsNh4+h7eEC5ND7MLIp1wTshakDWM95sYJ+Dh9LyEP4ExaZKW6OMF5VENWKb7HBuvI1+n0debEoXQGWCFhVxeX8wZIgSgbHLLFNRMuC83IP3fc3EwzypFZ6H59D52SAdzQ6JvuyjzVF5LqhV0IfIvkSLb7oi8EU2Ww==
