apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-jellyfin
  namespace: jellyfin
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-jellyfin
  namespace: jellyfin
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: jellyfin
    serviceAccount: vso-jellyfin
