apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-poc-reader
  namespace: vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: vault
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: poc-reader
  namespace: vault
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: poc-reader
    serviceAccount: vso-poc-reader
