apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: vso-global
  namespace: vault-secrets-operator
spec:
  allowedNamespaces:
    - vault
    - uptime-kuma
    - monitoring
  defaultAuthMethod: kubernetes
  defaultVaultNamespace: ""
  kubernetes:
    mount: kubernetes
    audiences:
      - vault

