apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-local-ai
  namespace: local-ai
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-local-ai
  namespace: local-ai
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: local-ai
    serviceAccount: vso-local-ai
