apiVersion: v1
kind: Service
metadata:
  name: dawarich
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dawarich
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
