apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-storage
  namespace: dawarich
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
# Каталог входящих импортов
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-watched
  namespace: dawarich
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
# Redis — брокер Sidekiq
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-redis
  namespace: dawarich
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
