apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dawarich
  namespace: dawarich
spec:
  parentRefs:
    - name: homelab
      namespace: traefik
  hostnames:
    - dawarich.biplane.v6.rocks
    - dawarich.biplane.casa
  rules:
    - backendRefs:
        - name: dawarich
          port: 80
