apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-dawarich
  namespace: dawarich
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-dawarich
  namespace: dawarich
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: dawarich
    serviceAccount: vso-dawarich
