apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-exporter
  template:
    metadata:
      labels:
        app: nextcloud-exporter
    spec:
      enableServiceLinks: false
      containers:
        - name: nextcloud-exporter
          image: "xperimental/nextcloud-exporter:0.9.1@sha256:3e90a38976516444d05f5f6758e5d572ca559b69ad3005ec4029786e9daf9129"
          ports:
            - name: metrics
              containerPort: 9205
          env:
            - name: NEXTCLOUD_SERVER
              value: "http://nextcloud"
            - name: NEXTCLOUD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: NEXTCLOUD_METRICS_PASSWORD
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          securityContext:
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
  revisionHistoryLimit: 2
