apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sure
resources:
  - namespace.yaml
  - web.service.yaml
  - redis.service.yaml
  - web.deployment.yaml
  - worker.deployment.yaml
  - redis.deployment.yaml
  - pvcs.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml