apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rustfs-root-redirect
  namespace: rustfs
spec:
  redirectRegex:
    permanent: true
    regex: ^https://rustfs\.biplane\.v6\.rocks/$
    replacement: https://rustfs.biplane.v6.rocks/rustfs/console/
