---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs
  namespace: rustfs
spec:
  template:
    metadata:
      name: rustfs
      namespace: rustfs
    type: Opaque
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBfAmkISW9MYmz+XOGLAKSYguKJnluEQgUzG3AJ+609fwjF5fi5zlqWlswtUBt8RqpKVeT2QujQ6jrpCj9AcWsNsHBJXrG4lc4nVUIyUmoI3/wRJ0LHq5QkYBZbmzO3pULsn5AGuPfheC8c1M/Vbiicp3bOY26i+IhpkS7ViX/BPzgM/juIJgFMDRA2kmi4C+kRAu3BEzgFsC08SsNfYLUzYf8k0cLy+ggXg7UXNXyGuKAnQEZMJIfRDzFGkqeOveEnZTEe8qrHjMlXThoBrXIHtztbEf7icpmI9VWrQ8ZIqclNpCykRGiePOwpAGVtnT9+SmTWVyO14GbKr2UcPXtnvv6cq6R0ppCvsNQRUWqf2BgDHdeYsR3jMXOjG+UBovhCK7FzHJTk318f17m0HNKAbsYkDi0/HicoUT2t1wuSbV6QHKmAMy5UalzQo1ECN5HxMIAtipSgdpvdZiDm8wsBo6KmYmVqmI3wlnybwq63KktIFgr1Dkak8mQiN1a5XjRfepJJZ6RdhrKHY2Z8YFyHLcEQK2NNa120bOYFwLHi5LFM/kUmfdbk/XDCyAfXIm3IlO5nS44KGurHZkY7UQAKN1TfWsJmAuwmaFARs81D2xqEp248nW5Ffje8uVW4eIdF/acdKqRWr9nFD2WU44QDybk7pZb+sd8HD6hi3kZTvetOc1Miotnh4rsTK42BekTEgjeAPfN/IhN1ypPY0sWsm/RZvvJOky0=
    RUSTFS_SECRET_KEY: AgCe3rcJa4XTjAD4BahS+NHdWB432nsFllULQQVABM6pAqQj6ePvOAJ3mNAvXBGCVw3pNWbyf5V+L6R3XgUUDoc/eWVNBlfm+HnsHR8Jl6yo3aitZ9MajB/v0oOm+JU4R2DR2gcBMCS8RqPKop8EAIkyIy3HAZ8vjJdpvnqR57QHt2wQ6yNp5CeojCwVT1sy/T7wngXKkaIZiQ5uIwYSTdBq4BzrDuwRdc8hXIxH3PRS3kl38bEaZNaUjDAJ1Yn0vh6EMjg3F7rKDV/B4r51qTZRn2iH6nImU6Qnsh3+WxH1oki6B/qVJoq0fQTFmR6+QM3H0Wd8jhstm4jfbWruABotK8aRZpkXdSokAn4LCS6AfNWKX9flHyZ3yFWrCa/sUflIi8IfiWfFjE0gcBoYlMxb8fgVYy0/hlFofOv6auYO5g1XON0VcIyFnrVXOm29Gb5Q89ZmQYC7fXyW9ylOKcErMDgZ0vMKjBGf6r9AtXZsLyI2cIdUNt6LdNN0wKDJ1knvgZr1tukVPvdlN8Q9nE47PX7BAij0hHC60lyXNDNXAfk79u4GIVSX/qndAghyjRiRWDMatmadyX0w7v4FD9bOS/KV9vBYWhwQynk7cwDSGrgoFWNZoANOjbZsc7mH9D6rOWlAKqjc35u42Kx6u8RMm4BY+I2XLl98ZVOlNVgzEs4RDnwGyOF7nHPAjxnbOxxBEhOUHYihSh5e8CQDLSHMamXW3yDeYGzBz+CnamSmd/vQeZapWre3ERr584lPuQg=
