---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs
  namespace: default
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgA1lFzs4lAK+/Lf+hW278qsgsCBahCuGREkslP7TKUNznfo/I2y/p0Uj0y/39notFCHLvLR9kApxIE3lTXVNx2q+eoX/OmrVbPdkvdgIz+xUpIvC94yH73tNxinvtk+V4TPjluUtBywNDWwH/46Tc/DIpNnxzLLumi5mpTOskiE46sP+C+8zj4SLVPMG2lxXUJr3jxuvcYmYx/QdefHKiNoIFJJXL6Tc+SGmaJ1syxvQnQn1T3w7onrFVO6Z7E25EWlNJxtpfETJQ8DiQAV6P2bAqn14gEKW4g+TW8djdK/0GiBbSXuC/YaoPh4gLB+9ugwOTHQslb66UXE+Wo+98QQCc8wU8Xv5/tN+S5kqA6Lqkra68Zp4MXfv/lZg1gcl2fRFZiMvcUufI7erYkgYnVoktoGCgagHz2zOFLqSo/q0+7NUiCQtMDpvO545ZueLLrjEiTzdnCIPN2qAaxpSXQidIZSYTWeAs9CtAjc+RxbqgU4ST5skdffwojuUN9ZSn2IZmR7pSuSkyFW8HeFSwqtBpup/3Q+/MA658OgyqA/VQQGUXfNnPMsdSgtTO6rrkI06qh/W3Zma0TkdXnAiyT2te51EIEWaCRYfUU2DSBC0+3v4BjZLLG2wUmJIvtFsgln4zkMwrA4TG/hMVcA5yz30/dEBPzJH2buoDLvYiYy2f3yTw2tOPhSRvZ9UZCRD2VLHcaqcPJ2M9/drWqcoc2Q8o72Q/CP9zU=
    RUSTFS_SECRET_KEY: AgCUU1ZL/QZTHKZp3vUhw2amvFKHVtmCLHD819xdxRFMQuzVkT2b3FNG/l2BZ5IFAk1qvv0MjG30TyB1Y0kNyQf2ghWKnKsU8/WaC/K0K+YD3UPZ7J9tV2SgTbMWay1oJNPhVwaIki7JTU5yZ+2DBxCx/FRkUJrrucbBt1DuP4DsJR9c+geo3YBwgKmTZADySVZUjYQoqxInLETzuz/9Uko737SwGjhuucv+Stmm25yvJCyly8iBGdZ5jfMShulqdbdzdF73TbDSSK+HD+legUq0kPZ962JqV07dAuzb4YegWKQyVmpa2thShfy3vr/VS7Nh9hRy3G1Zqaua2+JTVs1yoS4yZe3mqdNLaqDio4AQJzWrR63lPi4UEQWGP+6eCqmlxVvIBH+S3n5qL1xLbSInh76LEJNuZnCp4TfBWDceB9wQpzcFlv0kplklj/Qz8uWIHufYAIZ2HFQFBTR+kYSXkiSyHjn8b44E9fPZfl6jNdbpsPfQ+ZWkmBG3i0ss2LmTCj9YdwfpPDIHR1QFs/RHZgeugOBKdHwJLxTYXKsnPmo4f54So/3NNNdxb5R9ze31d2E4ohRLo9LMfvUZDN7uQBKUS32pLz5DwZ0M6u5d2HevzSTPmMu+S76WoD5ahLGmMjDe/pZY+5c8whzexExa/vVXt2+fxUF3gQmszSLttOYopufxRd8ho6QI3+m0sW7IN5tOF7h3DCwqDbknGGKunnit4vzLUWKOp97kSmleKWiAF3b4r7cqSilsEP+LrJ4=
  template:
    metadata:
      name: rustfs
      namespace: default
