---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium
  namespace: technitium
spec:
  encryptedData:
    TECHNITIUM_ADMIN_PASSWORD: AgAS16OULgVwZjG2bJ25Wb0opqP6GIIWv4lK1lyNiikCL8xVBKvALQ/RgFV8asuh+2jXlVh96C6UH/KDsAlfP3LrIXpqKlvSRrf1NPzfKE0tWcS/NrFtqNjY04iI3zAiNAwU5IVQQmDON3X3gwNY9XOzx5glnSsSzkjwB0irfOWpwp1e2dChEtRS2u/Cx4BZ5XwBZ7iAelDpGYiWVLPqpxpjtH96Kwau0xDQ75HLOPRahnS++uj4q7v71cYmGWjNbjMOEC8JO/Er9GUOu2jnPBSisldWy98DurFmTpDwf9YVdx6U60h1IDNaPxAEhWL//1cpbx2biFWcPJACuKEtlwHs20GqxpUM4xDRKEf0VDdafvyjWomIAf3zlNIgoiTF8pBUuKVKDpwIUcNI+XfIDS4g47UECWyKolvdSvc2KdIVSubXc1SvVhSIw7w6MXn7Bw4m80XJ/jNi7FxDw+YJcnSJcR9dRRxhT0HW67LzOJLc3NuQRfOZKhfRhFLCHDyYMLgpWWK9d0MzTL+YPWzwUt0e4iPEy2yZ5FZgk2RdaBKmid+mE/0uNLl4hdHoB/l+M/Jmws0EKbNEKPM/CGXM1T0J7F5Mi62RgDO5dhU1Fdr929UburcOHg82vv6Ebow7u7Tl9qGgudcRSQX+8WzIyi+HUfLCeWZZDBXs8+2q0C43Cy0KSdasBxoFG10EXJoqoiL1achc9Et7nCA7/pJYaUf0jSP6fEeFNDzq4heqRpadyxAkN0AJJVZJmN+7OLnFDWI=
    TECHNITIUM_METRICS_TOKEN: AgBE/yxOqTMIc4KM/vzBRjOQORsfwfoKwxcvbH9tVx8oa3VQEDX9sjqzTATBjjzz1bQpO0T7WyHhGpVEgoO82pEnsgtyU/w06vohY/5bhNNmm9+4LyUvvvFBjOmFQj6sXYBuxxNAPKWl9sWYRbIzBJJTzvng00X700SFknxTTG7Y9iE2s/rwxVA+zQOjHD84CaZSnu0noQiOhiYCVDWPTvQwQ/4RM1IZV9S4QYrkr9xcwfKlpW7ZuNFu97Uee5D4EHI5hpzMkPrGuj6Y9pCyDkL+XJZ9QKS879hkI3ed5A3e+nr67XRWjaAB2HwIdSP3etECbNSvU3C3j39xRh8ubJah3Zp8qu+F3Ifu1TCoYTalYSi/W1g5v6iscPBV/O6HD1MZOuPudJk+VmnSyHcVNblpSfOhzyrHXtKxFFfc3O/NrlycjPjKsioTwwZWbnJH4A4XKvIsW4wDWIdzweuHOQF0fv7ndLdYbZghDs+ptJbtd6BlHrgly+5b3CrWV01sIldMTBb9EZj1VTnxm5sf21CXrG7XjiIfnuT/hCcIrZ0L+wA3V+8nqy4TuEmL2NPGJB1mO2aeu1KqnA2YsgUsja3ZuVKWHo3mh1wx0Mbuedl7x+3/D38e1xMqUXYzpvDxk+9dq3b2tnGdTW9BluQousH2LW/z68NV4SZsqsx75S7JjoVw0F+WVzXQvJnRlmUtlhqI1MzTyXMs+3MZp4o9uRyd8Cy90czO3vgW7LWbpoSI7mq7gEmu+FE/5cIOfr/aHkrnLWE/PNC2T+LetCmUCa/S
  template:
    metadata:
      name: technitium
      namespace: technitium
    type: Opaque
