apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - homelab-config.yaml
  - oauth2-proxy.middleware.yaml
  - secure-headers.middleware.yaml
  - ratelimit-default.middleware.yaml