apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jitsi-auth
  namespace: jitsi
spec:
  vaultAuthRef: vso-jitsi
  mount: kv
  type: kv-v2
  path: jitsi/auth
  refreshAfter: 1h
  destination:
    name: jitsi-auth
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
