---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-sync
  namespace: default
spec:
  encryptedData:
    UPTIME_KUMA_PASSWORD: AgBIjKXEtU1Vh1i5sQvJPD8nanfaJIkix9VAVSL3g8wYyTfgx8g9d8xlnMqzdfAR/fzj6jPM4yuImCAVABfXTjfHbakMM/YFxaufWtI5uSjFiK5X6a1t1PRu6omQQQWSJAJUymUs3PmTexYSJJMf5UwGeCLWzn1scMpKYjTUvqMsbpMf0NMDkMwaZz7c1UeAkDl35f7wmIDBqU5ZR4CU2E9P8ljibw8cDTmeOkIWv9hDLM+4yurtD4Uac/Tv+6wKejUTzypP5cghR2PZuXxRAMxAB/Y0dL3xSvZPiWYi4BWYMjVVN0lOv02HdcM420luZVUxoYGCHh11gxDed4TMilXvLaZu22XLSmRlyjy3Cng5zN/QBqot4oiWk5ZquAJ1yX0kgASsAiOsEXoi6r3ckRpP4qmgvkQJu8ZTQbRHbNOuR0qmcL8sWJ1P7gPpHhYzhtXyHIhm/9HQLlCOHoFTDpOQZ2MfHr4Z4FY+/9Q7hpqD0CFIVGK05xE1MyiWHRskTOXHhcI2oKzte06Yyk+p5GpNmxgldYhroW3cQDGl3beLmxGHuScWM1ubX5b7JRa+rTowc4stpE+CtaAklQGXsEf+xqbhQNyUFX2hJfsoKVIOL5yaGxsxzioU7OIcXAdoAfq/XW2QOIKyxgBiggTPil7qPmLDT0O+NJcwNT0vaNvlq5MOiX4PgpUuINmqXPkJIXpsR/DIZTcLdky4OYEnTJTPPhnEy8U+aGo=
    UPTIME_KUMA_USERNAME: AgCa35ibuJMdtx736Nt3njNJ/vqTzRaykNQ/MKJao2keVb1ImR0sdrkEDyGzQekcc+Kj0/PGc4+3mvO3WF6XKmPSSgJF+BON4v90HHpIlWC9uCh1vemnXhl6vFkgwgwHJcx4KGzXjpix31JPvU65QL2isGSvxPu/KYFWN/AlD+/IrURgPOlPHMJ+pbjpOWyNXoNCzY0vs7+zmftClkqIZyV3Gl6LVFBfDi9SoyWwOFEZMLbleO0lDyZ0o070wrhSIPoqgH+WVedU2QW8Am6Yv79Mn10Dm7z2Qqms15zb16+fmIKEOnnQQrbsOIZS9eCRSG74HfCSEXgG7PlpTrkeR5FmHkY25T1dZYHeM5s8rOln2sXfko/D7/3w/GuRFXn0dstatUITN2m/8Tonz/osjH3BNuByekmN38fYDAq/Rp5+DTfSUzq5xIa60aw4qAineYXl8vW4NzSDmPgazq3WXRvQCkVFSAPl9Gau4ulbqmLI+Ef8zVbblABWrBhUgDeQ/yyvZ/5IsY9/p0y2JEoLc7nL6pLsG5+daf9xZzsNSLIRV8ZkdVRr0xvhiAXysNF/V/tY8nWa6EY9brsVUjcAvCP9hHdvbi3lw5MCSbTRyBOCyioToGFp7wAGJhI2XfDDSiQuSd1ODnx0ysNdn6lY3K3gFgKI1jjiGFKKqPpobz/2HYug11o/+Yg8YwmO4j6MiqgyB6bsMw==
  template:
    metadata:
      name: uptime-kuma-sync
      namespace: default
    type: Opaque
