apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home
  namespace: home
spec:
  ingressClassName: traefik
  rules:
    - host: home.{{ .Values.config.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home
                port:
                  number: 3000
