# ===== Service: выбирает pod'ы по label app=lute =====
apiVersion: v1
kind: Service
metadata:
  name: lute
spec:
  type: ClusterIP
  selector:
    app: lute
  ports:
    - name: lute-web
      port: 5001
      targetPort: 5001
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lute
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: lute
  template:
    metadata:
      labels:
        app: lute
        tier: app
    spec:
      restartPolicy: Always
      containers:
        - name: lute
          image: "jzohrab/lute3:latest"
          resources:
            requests:
              cpu: 1m
              memory: 256Mi
            limits:
              cpu: 20m
              memory: 512Mi
          ports:
            - containerPort: 5001
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 10
            initialDelaySeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["DAC_OVERRIDE"]
          volumeMounts:
            - name: data
              mountPath: /lute_data
            - name: backup
              mountPath: /lute_backup
      volumes:
        - name: data
          hostPath:
            path: /storage/apps/lute/data/data
        - name: backup
          hostPath:
            path: /storage/apps/lute/data/backups
