apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-infisical
  namespace: infisical
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-infisical
  namespace: infisical
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: infisical
    serviceAccount: vso-infisical
