---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich
  namespace: immich
spec:
  template:
    metadata:
      name: immich
      namespace: immich
    type: Opaque
  encryptedData:
    DB_PASSWORD: AgBI+7TxeGNUzQQLtmhvQpr5RIyRSVveDz990gp71Fd6RPJPkcjwkVAr7kLJygacMt5QinsXNbm7u3LQYoOLUvjPbZbcfybNg8Utb1/RPzPGvdCB0ANp9wBZLRi/cvxg4gMv+N0MwmeeU45G8rMcKtLd5voi8y/FVyQdIXaZjvbNP5UrezBrOBmCOcFyx6y7RX4383yHT8x8FRj1rhlbjs/AxGV8r6eIvqGsEh0RNdicBfV/dvOH4VQV7TZuCPhQyvvS9fYrdC/kl1pxV/VfoGWAAKjhUMb05Ri/B8J97BK0qePTK5krrcXdsONlQTvSl+qjc9EY0cxvYdtXX0h17dgxmwXsaDinnYPcUg8q76dEiuubiF8TWT1UND8oMElh7c8VQTw8QBz3lkms+ZmjkIp2Im932Mx//yqWSTc4sYclxDVhdt5npN5BIMPxqYd/kli51uTPG9lNGaM5xvEj8c5EE6fZP6Hemul96kFADZ+BXNlCJ9IwIprsG7TV+5GYEQUoSX7Owg61dgd+IWOI/gB4jGFqapnAns/oUOdyfMN0rKvMOflAzo+V6ozE+QyXXwGqL1ApsBG3lWeCiBiUfnSpCzc594I501fOqZ8U8rNrNF1HJ6FW+GGQdbY0j/+phq/575rV3dwk+65kQIwq19u4IVTu899suQybdPtI7K5ckWPQOfmTqp+UPzmwNmyLfo/n1Q0rCzwT
