---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCFurfZ3aCm4ojrGCGczMAHthiCegaSmq4bzC+54Cva8o5/hvQLFn/FbPSeWDLUMo+hMei9dkGE99KpS7YCS6F0qW/c/Nd9YjTIRa0m37SeE75erAqYPmUjRBgRy+r1a5QQklu0un9ryz9UdI1vEqgNVh6GUkHjRRJmUODiWtwQkBn9VxcKsWyVXcl3AOjk+9n3YIol71+/I8lRfd/9aN1XJeNoFj5958ExZQiQT6eNErIZlPjPxh2eJ+j1HBIklqK5Bbemitd834tbbK28S0uQfwuYn9h69C6PK6oDJ73b3ayFjnbKVDZ5If8YtGQovf3bJxKAkjOx0ne4pLZwB/GXAKRjE+pJ3+T6rhaLkw3E4IbkxPcAoVw5vmv3fCtH2Ew0GnSlFPAleuGWncHuCkti0Fwv6hnmxZrF0czqWlrAXAxkoNRLVYVF/iOw/6xueJPA8oCGaiHL71bBxNFMrOeKTNOqx9RCyZAKs/JjjxXz3ui4YBcug6jVuTB/kKp0mvNB+PytDylF4BzwkAnS+B/Cp97SM+9BpMMjrq6/MR8hEjHl+IIScmaqLiXGtMXj6hfTOjBCfTCIOxX2A031fKGKwRk2n4UWELRn4HMCxJHbep1gmCWrJICI/+AOZ/k3P9DqqQiGfAdPw01Hzx7F2Qzpbl0pkiaqGkbQjKRvCTDumUWtpP2YsFjSykKbeFg7OJHcPqN1wUBi
  template:
    metadata:
      name: immich
      namespace: default
