apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate-wildcard-casa.yaml
  - clusterissuer-letsencrypt-prod-casa.yaml
  - clusterissuer-letsencrypt-staging-casa.yaml
