apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical
resources:
  - homelab-config.yaml
  - namespace.yaml
  - backend.service.yaml
  - redis.service.yaml
  - backend.deployment.yaml
  - redis.deployment.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml