apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/apps/alloy-profiler.yaml
  - applications/apps/zot.yaml
  - applications/apps/alloy.yaml
  - applications/apps/athens.yaml
  - applications/apps/authentik.yaml
  - applications/apps/ats.yaml
  - applications/apps/beszel.yaml
  - applications/apps/beyla.yaml
  - applications/apps/code-server.yaml
  - applications/apps/gatus.yaml
  - applications/apps/grafana.yaml
  - applications/apps/homepage.yaml
  - applications/apps/loki.yaml
  - applications/apps/lute.yaml
  - applications/apps/mermaid-live-editor.yaml
  - applications/apps/navidrome.yaml
  - applications/apps/node-exporter.yaml
  - applications/apps/otel-collector.yaml
  - applications/apps/open-webui.yaml
  - applications/apps/pyroscope.yaml
  - applications/apps/rustfs.yaml
  - applications/apps/seafile.yaml
  - applications/apps/talk-hpb.yaml
  - applications/apps/technitium.yaml
  - applications/apps/tempo.yaml
  - applications/apps/uptime-kuma.yaml
  - applications/apps/verdaccio.yaml
  - applications/apps/victoria-metrics.yaml
  - applications/apps/zitadel.yaml
  - applications/cert-manager.yaml
  - applications/cloudnative-pg.yaml
  - applications/dns01-webhook.yaml
  - applications/eck-operator.yaml
  - applications/forgejo.yaml
  - applications/gateway-api.yaml
  - applications/grafana-operator.yaml
  - applications/headlamp.yaml
  - applications/kube-state-metrics.yaml
  - applications/local-path-provisioner.yaml
  - applications/longhorn.yaml
  - applications/mariadb-operator.yaml
  - applications/radar.yaml
  - applications/sealed-secrets.yaml
  - applications/snapshot-controller.yaml
  - applications/traefik.yaml
  - applications/vault.yaml
  - applications/vault-secrets-operator.yaml
  - applications/victoria-metrics-operator.yaml
  - projects/homelab-cluster-readers.yaml
  - projects/homelab.yaml
  - projects/upstream.yaml