apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-data
  namespace: beszel
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-agent
  namespace: beszel
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
