---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel
  namespace: beszel
spec:
  encryptedData:
    BESZEL_AGENT_KEY: AgAZdXDi2F8WlkESPcwaDn/sdADWFi3bzFofA7gao1ryovbuhl6l/tLy1vgC97NsyOX9iXxhlSCU524CMcurL46plZQXDS4/J6ybB53q3tku/SEZZgJYriH3Z3KHKbLqHjg8vWP65GQghtJOGAuLP6+GjsxtXQNvqF4UAkVLrJBCc5uoO9tBZY7AY8sTIwbK3r/mwhsTE5o0dx4w6JBkLMXOsYneBdqOm09oIqSu89W2ISeej6uRPEiEQv5VJl+OXe68zarRPDqeiO5AoUDAkpMnaG3knl4eMQlL7XshhH3fM5HAIeaV07jhTF8u9/4sCMdmgyRzuEPHBcJRXCVjZ9+73h7TUKzoLmE10P/omRhPiJDffoBslhEPzz4EcaRwmau2cqkK1/SPpR6fS8arYQXTwg34C+HP813ind3/WjrlRRQ1mNSaDavPQtPhWyIduSiSZSwELNy8HJCPP8kqYSg2rozEH25ND4saHSKSjvrrbZfcRGut9gsoZMac0nFN7Nu4KY8UnVb41RoXUJOUkFWVQNZ8L6TDzZTRPU8pwtqwPuRfebCPbpeteswWLOJ6HQuAcqRxXnFRRrqveo0hZrFT5a/m3y8gKtHjt+Ql0C1na7f9ulM6+HYNG0cKWA5WUgOWFDMk/20xrlnfT0z5S1mjV6+45zX/ocOWSwFXEd8y9dEXu7uTjqQv1pUQhrzBkc/TCUTWRwOUFmtBvtvqNtEijp6UKj3hQ3bBffaYdMuyAOJ0Q4rvJ5WyAjcIsvtwai0nreVxfBHonQzyVuUYj9YypgTo1MK2vHMoz64LIH5yDA==
    BESZEL_AGENT_TOKEN: AgBWQM1Ki5HZTinO6s0sjQ4z4/RgS2IfsQGJyvjiPXE4Ik/tHYIrAV01jZCUAsXTM0dagW9ZhTTvpoTXJcM5/Cf2YstCzsPyfNrzs/27S1Nbl4QUDD/cyvPdyYyvdGcU/DP1WcYVq7zJlXF0Z+g+s9EBiouocP37LAx5DkgzH9ceCLCvtWTQDfEEjwbT1K+Me24LKEe7m9q7Jo4qRrvuTvwgrWFKoIWReOdMItlML+wMybLpYc1sZ1IaKdPAl6sIJmHhit3XuFKXL5ZA1wTh/h9Sfz4lXZvGPsT8GeEao1knuhJFqOKJhYHTZtBvZrrbG4ftjBQ0ZsahczJpKXEC46VYEbDzTmWt8G+xR1Mfy0CKtu9BlzVt2GhYqEJ8Y0AE4/w9buF7/eu3abotV0lAZgkdFIvEozU3gi8B93/WEEjAJdjLAZ6VNxr/FHUVZb9mZ9SPu/c2KZs+qssdHYNpl38UEyrcpuEmgxAIsA709xLBUa/VAsk8U+LvWV6OIjLTyX7UgmjrzcsF/oIJqlGXBjtPgoKmlyA7U5wU8DOsZbxcgHNr5DxySyVIYeYhC2FQpKU1khr6y+o5QK4LaOJ3x0IOn8NTHjng0Eagxz0UhwA47+LLVgcNytCkcD+iRNnQVtZp3MMvBP9U9HkncfD/z2v6MVnkwURP74HfSjRAU9MSmxo6zPhYwbKbcT/xb5vWNk6fNAdQgGnd2i+nKu98ql2e3n/+k7MrvGrPwYqjTUjrKMn2Mbg=
  template:
    metadata:
      name: beszel
      namespace: beszel
    type: Opaque
