---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgAOzE52KOP3XdZ0XxYTtR6WK+e+Bs4gqCCnlWoOBanb8J2vL7/vtdYz84iUrUK4z/qY9FrhISExWwPzLu8rAVtG+2hqy7tpPoBfGuylMNibe51RujfEcDkOT8hXYK5XFhv96LuckJ2K4iiilaUol2A6F8J+TllqW11P390j5sl/jX/Q5Drieevz4xXrjxt8HgPG2mjxAWPF+3kkkDlD2oe6boQcfZjLWsbFTIMkRmt+ux8BmESEEoe1HNPE/CvPj6UGubH2q35y6DkLoloy/8uM9AHtuB8FCK1hn8EB/r5pAZ/Zsl+rpq4hoUGq0BRPQeZ3g6tirPeGl9RMiRkjL3puJtH/Ipjlz8kTNafuwQ7JqSv3weJAJcCTYQ+UpsFWgdMn4zTYBzfd8qI1YHMvNqPR/2LAaVEZjMktOX16t1QMyQ5bqgLUMFNfBTpg3JzGftAwZWgUZCAuIU0Uo+rzulUumKtdfrkRIlfHKQzI9aamIEE7MYR0FuhWV9czej6DV4/F4+X5ijgj79tga/3yLK+kpMzIXtH2pLgNiCsAZhChs/vOJ/5u+13MFUtuwxr9Yg9lThXSjdk6BjLh3uOS6BQCuP+BCalXykZ3orna4pnpbct4mQHUPVFFLc6PO2ZBjJiJOlesQrJVDUG45k9tKbkRBhaoVwPSqw4xQNRNc5oLozLRDLrOTar3rYPVLqheOHdccPqEDfIN1W6rlXjLO66sH2/Nx2rKjNqT1QRxNP0MwmcnWpvysp/GgKalVTF4/PI=
  template:
    metadata:
      name: open-webui
      namespace: open-webui
    type: Opaque
