---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui
  namespace: open-webui
spec:
  template:
    metadata:
      name: open-webui
      namespace: open-webui
    type: Opaque
  encryptedData:
    OPENWEBUI_DB_PASSWORD: AgBMFIEGGR30RC2hznFurZCV/q0U/R/pAAnKprGlL6tA+sLxaswaEdBg44h5qtwQGLrW/fswY05iZBqPhgSA0vgJ/JznZikR4tEEdnu6ebhJDv/WVNACWly9NXfF3v0kcyNJMh2eULTIR4TbTBfpNdyeZizO7Lx8G/mBYc+QyV4oYLoCbDjXstayRxn/WxNS86kTgI0rlAkQuVf1u1gJp197+FxIBUwxB2fQrOYdZUmgXbu/rPHeqT2KpwzxpzNlf6HrB47t+Ene9GNPuQL+NjfOIZm0nLr0fKf1ZFwNpKlcSu/ZJPIPWIUrbI017FWj6pY7Uru9qsz6D4V/NOmLjM5YjjOY6heAMf2JCnQssviSetu+h/VErL8LkFIQKBZw9erkHBPIzQbhE7UyvMri8zHoHddA6silwNXEHQqvw/vCC5k395Y15sRAkNZZ05FlrD83szhN6BR5MGhth2BuvLm7pVU29P8GalGjRNAkVXywVmpErysolOFzxV8lq1fEL0RSMH1FLs7TolizNLzN3acdanzuPFb9MsLz1UWSar6OBcqc73Rg/jWZEG/12zhWlBiyHnr+hpRHobDj8oT9hPuEWNEdBtSpz+j0zbD/7Yp7E+LF2LpDItumXQdNfhVTICtEBthwaQRv9RaE6Twb2rPpMUv4eGG6oUYPvsbGBcaGD31EaOWb8aNi7SU3yx+KXLsyvi6Udkw2/yv0KPVgXrHMs3+xIMVjxmSEK4+dhlS6RScZa7PyZYNSRE0v5JgPmM0=
    WEBUI_SECRET_KEY: AgACkW6mf528FBdLrBBscsJeFS7PYshciH9NzdDDcl0eV+NCDKsQ006AwszavEDj+V7/iaucwvzMFPm1+PpRQGg31X4yqgQ2l7wHHx0Gmi/69WMjkqTVpsTFLTpE/nt0Q7QmOUYPSoMpssOFVLxoxdnzMvz9EJmBHSa4O4ghjFSGrWyAX6ZsTz2hic2voq4yTswyjq5bNs6yosUtVhAQvrSo7mPFBf74Hp++OWq/M2SRw7Fd67eQC2ZBspCS178qAtOmP8I1Il+VPA3acg+WpkIn19BbG8cGdI3tyFxQck85+gXpycAv+uLufYkbFp6Kypxorkta4Nz8fEo6OX5v/qU2AFp2yq10cOs6KlgXpZTdpqX3r2Pkkuzsr9RVxV1wQEvJRbXeAD0dAxs1M5nPQHNh9qjhbg8KN2AhyPbGZnG+9iPtG9xOhPKyNZqP8XxeFXlKcjqANpRv3ov30bCTwcB+KV48BW78s2CJp79ai7hAXYKGvf877iLzxFgaw8Zv/SPx9J0NoOktyCLmyDDqYYFo3BApnVJVqjpBZpOMV0yDvHeOqKMsPzmRNuD7aYPOrGiX1DpIixWc4fNyNP2ljJ1zDifHo8+dvmIcmXWIYC3O4Z2nDMp9iqUCHubIC2Et28kdM/tM/sOJ51fHOdxzkcnzUKrqxX34m33RPfRXlowquDQtX6khqHx51VvjIX0bYDD0erltZwOcfjq1iC2RKAyerum3eqiMtk0id4rLib3O9lMR6ETKAWyDng+IhZjSrS4=
