apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-db-auth
  namespace: zitadel
spec:
  encryptedData:
    password: AgCWxiNxhSAik3fyFFTBDU50KSpkoGSav6/wyM7KpOK6YiGMiwUH3a0xRjMf9v5sDqk7+fZ19kxr4NcB3rm0QsKX58lmjKRDTF8e/SEqi/nOr5kZVBSihAUDKxEjwp2KJdSxBqnrNhi6TwQfRyiV2MyhARUFvSAFrSuNMZ7iXWB5uEfP0eNqHmsdVvMq4Zt6fHIh9qY9nNS5csczKRwwPHOYxqQt+E3rYyPh0w2rSTe62RrHsATQ3QnPhe+9nWGk+ZyzXmqURjnO0WVKb8/KxLzK/7OVtHuPis/K5p/WP0tOhv3d1x5pgPmdHc+d+xFD5Oji8bD1gp9IDQk6DprT0mUb5bKGL2jC7+z64OoghilMmyYhE/iqNFTOBQeLKZvb0hcFCQAsln1+EhurDOxFPBWqM1SnqpRvaFHBJi9x2K7MapRpU9urSpHNnP1iE1NLksoFpNTPL8opcD3icpUGtqqXmoom5fasuIbxTmhdnMSyG/RPFVHj57SQju23on9eMrRaYpc2yWu1M2VtDWgvFSTQj4cbDukMMzHRqPL5Ng12I347haUGeDt6VlKVnqLaG0gpwxk4HJ48MSz+7SXqIuMK4PL0LTBGmMcQoOhzFf6sMVcTb5+XOrcAcyAonQjMAHlcgk30+KO2e2jvUdrSLE6bHZcWMTPmJGE+Mt/3PGKKx/ZTH8CgmBvSPdgMJy2/awHvINLrR7Ls5HvjE/dZiN9sVV2rfDFZOBuPpiaZBTny4TnG4ZvZuzsMzlGieyax+/4=
    username: AgB5St3nJfgEutHvS95O/ydbeCJn9WQnw7hGego593OJWtCh5L0bTEHzOVgiTzqRFpwArvYB7ZvxBMhleAnNVgJMwNnebkdgvGi4J17MwwVOqRPgpN43ob9Hl7pqtswodAugtFkkzEnAe8Nojaj5NgMf2CHcn0JqhOEhAPH04YY0IV1pQCXHZHftq+GIc1G2jP0ZbC4epEzeMuKHYisAJWY1PYZ2YfObGPoRQNMzejyCiP7UcgAsYC+VMXKOnpLknC+MgJr507ox27R4cE+25Vdn/2lHSwknyExcM9lFdd3JMOqiuchX8ai8FMajc/Vp38Txx1Fra/Ww0M/4/TY+CCn0IAFpxuFj8JIowGuf1bGTg+Ice4Bjv/WOd1CEBm+4X3HoQSF5Lqawg7RyNMPBUIhwTeJP6UY1b9FWo+8RbmcNQsFQSGnr+BgKqxGlt4we6rcQZaRW9V6prYjeIEvCCdm/FGQKXZffwUWnPfpknpIzim4u0Dj3tgOuT88q+IQjY+eFWuzlYVfTvdpiwW/VZM5ob3Q4y9gH1Q9tMIkI+nVkDbUtaZjSevBZVn4lsvQ4PxK4fmN9E7IaQvqo76ZOAT+Smp+pSQ86JpKLqmbJcqiXLtmZtTyu+djKvL8X8oRtd1389zZ4BcJpAdA/MKzoYgQXmwj3VRPcSvmAo4ISKUdF+Ut53/1YbzziCB7nra3wYz82B4cANrsN
  template:
    metadata:
      name: zitadel-db-auth
      namespace: zitadel
    type: kubernetes.io/basic-auth
