---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL_PASSWORD: AgBRSIRU4wuDOybkl3vbl31+rMh+LmwqMloScuoOU2Jy4uttdMQzE9izDoP6k0AvV6kCPcZ9iDw07GogpZhVMGdO7CJwhY2aoM+SIK40lpqNLc9BMIMwMX8zLxQWm+hM6QCrIKaBWyAAPOgB7We1KwNUadMc7qQpXLYQ/gMCrJekJ47JtHoj76Lumf7eBcGwE1CVIBS+01FPmrho9T6NUzK7jorfPHS7a4A07zSUzAJG7HR0K5iz8lhFFxCGRdmMoZEd/mseByuuQ8Em3kh1BgB9Qc4cdLrIXbcSTY+Lc5yIkfApL01OdYVSfFLDwBnrJ75xTI8GDLFnjeWHmk04lUHQh/cKO0xOqv9FZUHTaKFOJmEU9fM9lIUvuOK+lHWR5+Fjs8TENelI7VQOVZHygQCXYMuxQ7IaK5t/IZnNDoO4JmtH+o0WrFPggYm+j+c3phCahgvHJ/+Ol1lxapJk0cWiqTO3N1+OQemSLLa7Oe0NdaBBkWA9TtA5l3gzDmJQb5Np/AMX0Qr187iq1BBXhuwTrWqLL1pVzPC/vTccaZ9scn00knGaN2dBVgO1qxtkaPudWIK3FsQ6M0hUQfcX/M/GC4gFxEv4K1QphHHo7GE/Qs6sc+N7s7px2luX1N2+rHt0u0aqCQ053tMjlrR5W+XI3ZIsWdRmlXzbVmKxfKtAiDfj8XaJbIcwsejjETxEuFHiu4n1RszIVNSbGJn8WXVCl488aqlPM6MzECuSUSK8KV58B+IBkEk/aD7jIAk52LA=
    AUTHENTIK_SECRET_KEY: AgAHUvyvcbqsSAnmOfw7vW7i2gAGJn/cP1csu2hRa8c7NU+O7FRKz4EQyc2nDhh/MEhEKpi8l+Pg4n7KWzFaYT5RTZ8F3IEncF3H3relMEgmqeQy9FX/H+6D9WTmd0533bNF8e+TSrBZYj7r/28exi/UXTKz/1EgnzWye9cXmW//rSRvEds0nWXo/sDJczf+/PwnVmRJJmiZEwGpZCtT+PJ5Nw+Gm0wx7jvaBswElBQCjn20kZ0MjaesgFokiQJCbVisYnZWHeJlhckxnGgHcCA1WdNGGbNOahutETHKrHRC9pFlR29kniMHpKfszep/bIvjGwbbCZthOLVEts1rIsoIpoMAqpRhdhpdrc9XVNHEtE2vd5V9H019tG28jIGSe/tq5Jv+EgavfccB2WRUs2w7FNPAuesnnUz3d+LSUtpPb3WnZJ2DEYoUXYPXC+ptanb5HG7TuDy7NADzhrXFqnq499/zTdRzt/A96s1Z1A13IOaCyivsazDU4cLs0UUhbqXDebJFCiwXik2jTohcig6UfPaLzcGhsfVfTNVN/0zl+0OjE9waz+an1KKWhuAc1fB2nqvF+rVk9VMUCnIqNAkq9ctOAkUbgbX0yLZkhwXS6Sd1Yen42ZSjlWw5ch1WS3vOZMC2azpzXV1bujqVRf0cbUBdGH180N/bYH9r3myHHFKnnKC9I0M2lfc8EdM30Z+ZsoaCczpm/5Bwx4Xj4XPzP9ew9Yco3r8Jfvddv4G8Bdt0S7YF6i5TzgK7H5Hx7WF3WNMP7vYphAoHpDMYVCeD9GeMdyu7Y46qraqne4bwSw==
  template:
    metadata:
      name: authentik
      namespace: authentik
    type: Opaque
