apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-db
  namespace: authentik
spec:
  vaultAuthRef: vso-authentik
  mount: kv
  type: kv-v2
  path: authentik/db
  refreshAfter: 1h
  destination:
    name: authentik-db
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  vaultAuthRef: vso-authentik
  mount: kv
  type: kv-v2
  path: authentik/secrets
  refreshAfter: 1h
  destination:
    name: authentik-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
