apiVersion: v1
kind: Service
metadata:
  name: element-db
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: element-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
