apiVersion: v1
kind: Service
metadata:
  name: element-redis
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: element-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
