---
# Пароль роли synapse в shared CNPG для пода Synapse в namespace element:
# пары «databases/element-db-auth (роль) + element/element-db-auth (под)» —
# один plaintext, два SealedSecret'а (строгий scope kubeseal привязан к
# namespace и имени; см. platform/cnpg/README.md).
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: element-db-auth
  namespace: element
spec:
  template:
    metadata:
      name: element-db-auth
      namespace: element
    type: kubernetes.io/basic-auth
  encryptedData:
    password: AgA7xWqotg8PA3BfSGjKqRTyLLJdZNqkAmlF48NPeSfTGJbo0FrRhR4/VNn6WAMkxqHkvEQDHcw77ugIdGJvEbKAnN+sIbESSj7VxVkezzOimARZ4F2/9Nt7qG/ifDOqexN9mVJmALuuU4W25qWKNR0p1trY39TaJvJh4dCN7g9lbcq+iuFY3E72lbEDO54ec7oDJ031f4P5KW9dY9DYTwgfG/MoSaW25Zh/LbQ5pAE6TVx0eWYP59GdlfXjP99QRDMwCCmlwKg8cWQ6ZDBPU6IUxw2GGHnuNoOWSZ7NpN5ZNbX5/eqaNCLR4iVo6dRR1jY9Wmw2bWn7o0mcMd678e1gJmcro2f4BKrr/AFANn+cb60urHJkc3WVX+e9PYQgYX+sLoYi2ndvuBRZ6UBjm7xMY6yl+6qn4nAkYWo3oyt2JAUDzK8E5L8+DIdxvDNBh3hUaRwatK2FSISlB7j/WsRJxoe8ICTaR6ZhDOZ38k3ztIv9rSLsRmGmzNiMUkzDal2RqYKt4UDHc9UZVw9GOuaCJPdWUgYXXRwaIMLlax4XvxPAoguQkyqalA6qqJ4vDfqenTbYmnacSCZc46LKGW56Ayg1p+heAgkjI3T+c+CakUitWiYdFl3sC8JFCSb68RzoZQjgAtdpvvgXSys7xj1I26qz6wLdRuJXDcnpZH9m2SVbk4BJmf1HH2zwbI3UaAERc7wA5qOZBhMWN+5n3MBphxSEMI7C0KdlROiI62oHzWTLoxVqg5IuQVNFNLjNEYCJAbVRDyM8TqJROZWHHfQs
    username: AgCg7yCmIlmgioi7XnFlrhjd6MuIEBreA5HnGjQo35eirhHtj6OQRGQIckWzWYpj1RN9/T0j8R3f/FgC0EnAsH9q1Tngx1JN96zNqRx8O7UxKCMwRSCK7nsLVO6KRbnduQv8SPzTwzMd2Vw9XCrMoKqgXisQ+mjhCIGdaaza0wpKZKsKma8gj5eA2qMjgjVe/PmRxJN71cEbQYPTIN4B+rOC3AcqHh7PncW3PqMsTf8Y7XRkHY6gX+x8kGg5O4Ypc+owhMPEzB9oY8ei0gsfci2gEM3oq8ct/5SiWDPotLv3nwJZEW6rG7WbgtBQxW7aOi9ENfqp4GBjSXzo0gUwXHqA7lXSAdgBUbkRXVH5y+9aw/+Dtbf+x69P8irTE5dtcT1P59S/j7S74qlythrmpgi+0YSW5CVWVSEgyVAJ71dTNS6JEzRw15zca4TP9RVDWfXdntxrgRiqThh+I3MQtGVY9EF3BSylQrPJH+1x0DD6W+4Q3VHfT7cnF9If+2qi+6AjBk8jeGADDoFQR1qLVFh4Eg8t7HTDGDMZFcphthSbi3hKX8I15RwCC3u4Xw6Lp0v/NyaDeTHGF7tCkQ9wMP7AaK01B+UM0Jna3N2O0w6dZ8guR0haG4uTSWZkqSZsxMfs28QemxYkdlUHaKoTImDwsVXbguwT6wlZkOthfw9NqzFNu7LVSo1X/HgThcyc0dXnFaDFNBz1
