apiVersion: v1
kind: Service
metadata:
  name: talk-hpb
  namespace: talk-hpb
spec:
  type: ClusterIP
  selector:
    app: talk-hpb
  ports:
    - name: signaling
      port: 80
      targetPort: signaling
      protocol: TCP
    - name: metrics
      port: 9105
      targetPort: metrics
      protocol: TCP
