apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: talk-hpb-secrets
  namespace: talk-hpb
spec:
  vaultAuthRef: vso-talk-hpb
  mount: kv
  type: kv-v2
  path: talk-hpb/secrets
  refreshAfter: 1h
  destination:
    name: talk-hpb-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
