apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glitchtip
resources:
  - homelab-config.yaml
  - namespace.yaml
  - web.service.yaml
  - valkey.service.yaml
  - web.deployment.yaml
  - worker.deployment.yaml
  - valkey.deployment.yaml
  - valkey.pvc.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml