apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-paperless
  namespace: paperless
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-paperless
  namespace: paperless
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: paperless
    serviceAccount: vso-paperless
