apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dawarich
resources:
  - homelab-config.yaml
  - app.service.yaml
  - redis.service.yaml
  - app.deployment.yaml
  - sidekiq.deployment.yaml
  - redis.deployment.yaml
  - pvcs.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml