---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome
  namespace: navidrome
spec:
  template:
    metadata:
      name: navidrome
      namespace: navidrome
    type: Opaque
  encryptedData:
    NAVIDROME_METRICS_PATH: AgCS1ImA79vz+cvmK1CTFy1kJcUTcYR0l7MO07Kh4DAIb2NyIUkZBgwCiV4te73GWtU6Q1Daq0noN+WADHIMtFkLXOhP03fFEcWcTzvi6qWetkob3Q9viCV9/qqrUrL3N02ODsMHhoSmvuPIcbCxZVNyTrLuvJV+Xj7nAFac608uw46KeI4942W4ie7hUGXFSBBmN6PPpk3EiYDAI/Ysvp+kfNCJuXBB35HchGjIX4ifLgVE4OE2AYqcaekrKeQVfHCzy4rvYqm8dhUu20xMWOzaZ5/4ET3V0kMvQCs+uNmDJgCh/4l5rqAO8r0e0uuj3rmLSXn4sRBGbdxlLVWJC9qkPJ34HmiEBzDdtX+PCMAB6LyV5YczBO9e5kY2dMiPMbGTuCs/vHIBGIDNfWne1Z4PoiNB4eVw/1kM0R81QK061NChql6wdtm+qiF3biZ1FZc3VBID9QmbDJT/J5OIYa4yFNMLa8LCPcj/tXUk1FaiwXrKtYex3+wS5A8MIrGYvCOqzLl+0iAAzgYfGbNUG9T8N/BUVzkmEjrHfcovyySBtZwRFmqbvTI30Z61z+vOAPsY35PlUPTLxTNIk8SmLE0AAv7IWYbrdrTKbCrIeYulTsdshAEyjZIfALaIAlGszBjhgvBlMQQFD48RQM4Yfj7glCJnAnESe22LrCE8kIkMaxMxQUO49ljeafcEMbscgJUk42y8Kk/EW+vmH+rTbpyi0UK7BBbpPFIYQFvhEdJlOM+MNI34IhisG6BKvjnPaQxuTdGNebhK2A==
