---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome
  namespace: default
spec:
  encryptedData:
    NAVIDROME_METRICS_PATH: AgA51dVk1yL073+FyGxNqgnXfXsivyuQx6JX7NKYO7aDz/XrOyx/XxT5l1RR54EVx+sB9xyTGsXxQMJnZxRlxOoB9nIO9HL98Ccq8Yu5rZt9rtHOe2iLaxgc6zbzC8l5/XiQFpzhzHorTJda9oa0kW7EEaHtMrZAN91yhpS/CL8THgUoqgPz6ExhV4sKvDTdVyxJ4M+qZW6FuDgdENiGIF2HaJPP05qkIWtXqnLOWI4xwxJsHxW0Dy9tBG+V4qAKNV65mm6lS540FTAbbjaYLjoItoYqDzva5Fv6Sl3MkkPo6jksjSbJjaCoZ7gZ/USVJHMudrWdD81zttoqS92Rn7nq1asEHM7xGITzOVZtDIIvd2TLbRR6gWYE08qOEYgUnFdAPeB7tE8Yut1VbYW3osuHfsqKapL3NfgFNrKJjjc4hNlohCLqz/D48RSonTIU8h0mMSDDckwkr6KBIoQbfTHVGdd9e888s7gr+0pmgLglt1JM2ObTrOLrnwStRBJQCBM50b6K3X2bSgmlgh84cgIGb0OO2FflReDqyrgTSvcvHRpHKpDqCc0VyvTpP0oXjdo8CN0QJotgL2J4+UZm8u6YGHqXnjQ4ybExTyakC82AmDTABzd1paYoElerNhxNcOckKzEE2irBEw52fSZaeCTB2vuAGACOVyOg0aWJIF8+9mgmwhAw2ZGfudzgvLQSPeb014WhEKK0dFHlrqzMwD25ipioHd+5jSEDRQMR6wJ1jTBCpZQR2RV6NQ9g5QlIk4g=
  template:
    metadata:
      name: navidrome
      namespace: default
