apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-navidrome
  namespace: navidrome
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-navidrome
  namespace: navidrome
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: navidrome
    serviceAccount: vso-navidrome
