apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - k8s/namespace.yaml
  - k8s/networkpolicy.yaml
  - k8s/service.yaml
  - k8s/deployment.yaml
  - k8s/data.pvc.yaml
configMapGenerator:
  - name: zot
    files:
      - config/config.json