---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-mariadb-exporter
  namespace: seafile
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: seafile-mariadb-exporter
  template:
    metadata:
      labels:
        app: seafile-mariadb-exporter
    spec:
      enableServiceLinks: false
      containers:
        - name: mysqld-exporter
          image: "quay.io/prometheus/mysqld-exporter:v0.20.0@sha256:abed8dac117b4ae5b70757f988e44795935b9a72c3b58d720c67ba688f8cb79e"
          args:
            - --mysqld.address=seafile-mariadb.seafile.svc.cluster.local:3306
            - --mysqld.username=root
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: seafile-mariadb-exporter
  namespace: seafile
spec:
  type: ClusterIP
  selector:
    app: seafile-mariadb-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: metrics
      protocol: TCP
