apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - k8s/namespace.yaml
  - k8s/app.service.yaml
  - k8s/exporter.service.yaml
  - k8s/redis.service.yaml
  - k8s/app.deployment.yaml
  - k8s/cron.deployment.yaml
  - k8s/exporter.deployment.yaml
  - k8s/redis.deployment.yaml
  - k8s/html.pvc.yaml
  - k8s/networkpolicy.yaml
  - k8s/route.yaml
  - k8s/vaultauth.yaml
  - k8s/vaultstaticsecret.yaml