apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-element
  namespace: element
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-element
  namespace: element
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: element
    serviceAccount: vso-element
