apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ats
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: ssh://git@forgejo.biplane.v6.rocks:2222/artemiy/homelab.git
      targetRevision: main
      path: apps/ats
  destination:
    server: https://kubernetes.default.svc
    namespace: ats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
