services:
  spotdl:
    image: spotdl/spotify-downloader:v4.5.2
    container_name: spotdl
    profiles:
      - tools
    user: "1000:1000"
    environment:
      XDG_CONFIG_HOME: /config
    volumes:
      - /storage/apps/spotdl/config:/config:Z
      - /storage/media/music:/music:z
    working_dir: /music
    command:
      - --help
    restart: "no"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
