name: spotdl

services:
  spotdl:
    image: spotdl/spotify-downloader:v4.5.2
    container_name: spotdl
    volumes:
      - /storage/apps/spotdl/config:/config:Z
      - /storage/media/music:/music:z

    environment:
      XDG_CONFIG_HOME: /config

    command:
      - --help
    working_dir: /music
    restart: "no"
    user: "1000:1000"

    cap_drop:
      - ALL
    profiles:
      - tools
    security_opt:
      - no-new-privileges:true
