apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/networkpolicy.yaml
  - k8s/networkpolicy-vso.yaml
  - k8s/route.yaml
  - k8s/vaultauth.yaml
  - k8s/vaultauthglobal.yaml