services:
  beszel:
    image: henrygd/beszel:0.18.7@sha256:a849ad80814b6a1a3be665304dcace5d4854b3bed7bde4dd1227e8ce1b82d477
    container_name: beszel
    environment:
      APP_URL: https://${BESZEL_HOST}
      DISABLE_PASSWORD_AUTH: true
    volumes:
      - /storage/apps/beszel/data:/beszel_data:Z
      - /storage/apps/beszel/socket:/beszel_socket:z
    networks:
      - traefiknet
    restart: unless-stopped
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://127.0.0.1:8090"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`${BESZEL_HOST}`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - traefik.docker.network=traefiknet

  beszel-agent:
    image: henrygd/beszel-agent:0.18.7@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    container_name: beszel-agent
    profiles:
      - agent
    depends_on:
      beszel:
        condition: service_healthy
    network_mode: host
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://${BESZEL_HOST}
      KEY: ${BESZEL_AGENT_KEY:-}
      TOKEN: ${BESZEL_AGENT_TOKEN:-}
    volumes:
      - /storage/apps/beszel/agent:/var/lib/beszel-agent:Z
      - /storage/apps/beszel/socket:/beszel_socket:z
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  traefiknet:
    external: true
