name: image-updates

services:
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.5.0@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: image-updates-docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      CONTAINERS: 1
      EVENTS: 0
      IMAGES: 1
      INFO: 1
      POST: 0

    networks:
      - docker-api
    restart: unless-stopped

    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  wud:
    image: ghcr.io/getwud/wud:8.3.1@sha256:42554d2cd50d5de7a47563170bd0629193dd1e086a1fd71d1ec10fc4c2409f5d
    container_name: wud

    depends_on:
      - docker-socket-proxy

    volumes:
      - ${APPS_STORAGE_PATH:-/storage/apps}/wud/store:/store:Z

    environment:
      TZ: ${TZ:?set in image-updates/.env}
      WUD_SERVER_FEATURE_DELETE: false
      WUD_WATCHER_LOCAL_CRON: "0 */6 * * *"
      WUD_WATCHER_LOCAL_HOST: docker-socket-proxy
      WUD_WATCHER_LOCAL_PORT: 2375
      WUD_WATCHER_LOCAL_WATCHEVENTS: false

    networks:
      - docker-api
      - traefiknet
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://127.0.0.1:3000/health || exit 1" ]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 20s

    labels:
      - traefik.enable=true
      - traefik.http.routers.wud.rule=Host(`wud.${DOMAIN}`)
      - traefik.http.routers.wud.entrypoints=websecure
      - traefik.http.routers.wud.middlewares=oauth2-proxy@file,secure-headers@file,ratelimit-default@file
      - traefik.http.services.wud.loadbalancer.server.port=3000
      - traefik.docker.network=traefiknet

    security_opt:
      - no-new-privileges:true

  cup:
    image: ghcr.io/sergi0g/cup:v3.5.1@sha256:badd075d6bf325cf21c98a95f08cef275bbe7a0d4f2abad6bd1fbc822e94d419
    container_name: cup

    depends_on:
      - docker-socket-proxy

    volumes:
      - ./cup.json:/config/cup.json:Z,ro

    environment:
      CUP_SOCKET: tcp://docker-socket-proxy:2375
      TZ: ${TZ:?set in image-updates/.env}

    networks:
      - docker-api
      - traefiknet
    command: [ "-c", "/config/cup.json", "serve" ]
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.cup.rule=Host(`cup.${DOMAIN}`)
      - traefik.http.routers.cup.entrypoints=websecure
      - traefik.http.routers.cup.middlewares=oauth2-proxy@file,secure-headers@file,ratelimit-default@file
      - traefik.http.services.cup.loadbalancer.server.port=8000
      - traefik.docker.network=traefiknet

    security_opt:
      - no-new-privileges:true

networks:
  docker-api:
    internal: true
  traefiknet:
    external: true
