apiVersion: v1
kind: Service
metadata:
  name: infisical-redis
  namespace: infisical
spec:
  type: ClusterIP
  selector:
    app: infisical-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis
