apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy-oidc
  namespace: oauth2-proxy
spec:
  vaultAuthRef: vso-oauth2-proxy
  mount: kv
  type: kv-v2
  path: oauth2-proxy/oidc
  refreshAfter: 1h
  destination:
    name: oauth2-proxy-oidc
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy-session
  namespace: oauth2-proxy
spec:
  vaultAuthRef: vso-oauth2-proxy
  mount: kv
  type: kv-v2
  path: oauth2-proxy/session
  refreshAfter: 1h
  destination:
    name: oauth2-proxy-session
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
