apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beszel
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: ssh://git@forgejo.biplane.casa:2222/artemiy/homelab.git
      targetRevision: main
      path: clusters/casa/apps/beszel/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: beszel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
