services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    volumes:
      - /storage/apps/uptime-kuma/data:/app/data:Z
    networks:
      - traefiknet
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`${UPTIME_KUMA_HOST}`)
      - traefik.http.routers.uptime-kuma.entrypoints=web
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.docker.network=traefiknet

networks:
  traefiknet:
    external: true
