apiVersion: v1
kind: Service
metadata:
  name: structurizr
  namespace: structurizr
spec:
  type: ClusterIP
  selector:
    app: structurizr
  ports:
    # Gatus ходит на http://structurizr/ (порт 80).
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
