---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 3x-ui
  namespace: 3x-ui
spec:
  encryptedData:
    XUI_ADMIN_PASSWORD: AgA29006sdkxO47cgyc3VRZrT38OLOtaIaGpeHPaujP02MvKPYTCXJ3LuvrxgjYpajtM+F2Z1m7U/69ePwsey+fQxZ0m8KOi2ou+GDlxn75XZ3+HhK6M7kQJTqL0mW2Ns1uZGcWuMIQEFIFlNvrt49jZ4Gal0tgeTwd4a7eDbD5It8W+4BC7NVUkpk26kodNpygp5tSIMc0PxQT9vUZ+XWx+AVpY68HlgC2H8Kwxle1oRObs2gjjHEUNek6fbg6oA+MWun/ktUilsYBfdm8LwDUJw+9Fqo8DJrVM6riTLCyxRvht5T6TfOW61bMiPWx88QGgI/9vTnXvPOo5IzxbAcMcCfle2UPDlpJ5y5rhzh+J1JOmgr66/tEg0QBIuiGagddU1c81rwXSE8fHojIV7COJHm+i3st86jB91r4GQiz0P8GsndwzaxO9RjDoX3kVR6vsE7250GyIlh1X3748JByp6AOGyGOedI69VLQDzcsF/+S0H4I+9sSTuzNWtL8yan7B0XIzZsnf29HWQYGvZqMg447BOZWy7wx81es4k3dA7DNeqeWLJ/cKr2N/KKIatpNaqWPFKjLMiy+xSjoBGBH6PC4fsDJ9jtE9OSHTgX97K+lXDW6Bz9ND0kU5n1dYLF8r+tHbxuAgllb5QF8I6BDyc5nCzKxROa4Hnp7O9DYwTY2ttS5FsgQu0h7wUlUG/rcC1nhVdFwC/+79zKXipha5qkXv32fLCtnl6fpCl229kycplAHgLGpE6tVnnbB5h/8=
    XUI_WEB_BASE_PATH: AgCVIMi2en100dFJFMWMMHTQLKCDI+r0v0J9Z8hC0K2hLuqzjHiFjPwB6qB9LBJ3VOwMELZPuCK5t8+hgSu2i+xVxZ6Pce/DIpwjnyRhxlwdoR4k+iFHUu5xTkrb0FitbMqRM7VplOy0Xg5piw+MFm7Eegnwr9aSswqBwhvp0bD7ZoPyB4p/SvNSVaPwGtr3SJlFQypi9WfYO25+5oplu0hD0u5Dn3HJi3lEyfjSCxKWSTBl4yAF2zJfkD7q/UwyIgf5QONrg+1Y2RT+s3kaCzO4ji8pJR8SbsQqgU+ZrKxn0Gmwa8Tf7Ssue4DG4dj5gUIKswv3IXn/K8h0u/Bt5bMm7D/5eSN6BvkhmrT1pe2yVnY/38iW6Al3gxwdDYyqLsOl5k9ifZSB8ClA/0WI+u5dn59E4HzuuHlbu2VAoc3iiZa8bIXLzJ373sS9rWhai9a+mJ+TC1YNVNtCBY+jdzhSQyu/oevIKXffj+BkNXQkLKo1uAUfsivkCbOx/CKayF5pxvczjsb0zK4e4g9Sv8uaLL9xUsUf7P9VI2pbfSa5CJCP8hCiIps6UbpASOG8+EyxoBRjo6iCuJ88yGyRVhG9Sp+VmLxX02iIiH5EdY3RPf+5v+b4GBg79eMf4p/kTYo684ytA0jR4n3nFYLm2IOEoG2xxn0Aa9Dc1wuC1D9U3JugUtn09wktsyXhtb4buu5FkC+PZw+eR+X17B86Uz6c/BZLGHqKudKwzeTcfpfbag==
  template:
    metadata:
      name: 3x-ui
      namespace: 3x-ui
    type: Opaque
