---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns01-webhook-token
  namespace: cert-manager
spec:
  template:
    metadata:
      name: dns01-webhook-token
      namespace: cert-manager
  encryptedData:
    token: AgB3FjrQEcAqYj1XxsMYWavzAjGPx7s0Sc3CrG89j5GhCFWhUopScOKeO0v8OjZ8EtDXjfLA2Uh8UYp+ERHInAoHTStn/wUZZUjhcHt36FK3jd3izIzBPut1IAwnjeIcJrTvnTx0t0mq/9ZkmYShcLqU0kRwcM+46fC3TMFMZGtIb1cyZS82g91tvKT/s6SYH+jtwkUQGrLE0CgM9z7d1uzbY+TJSSJyMzPUaZnjXXHVENSiYueUItkgNsLXACtTjDsA/OCi1TzFeJWeJDe2LOFFKerHAnWV/n1LRvFLON58NAMNaDLFN26tFwY53DldmfsoxqXh67Zzx9j/uhMuwXXXA4QYSV8wwooHsL00HTvGFG3/y3LhEETAMxRiLN7AyK/cxRunK7G8iGuVKjodf7jsUxCaqOkgaQCveL/zBGXiX6tdTJ9iwUlpN7n9F0jl+Pu1a3cLqqqo6NwktDmE8z8apY4J0Zwf9VTYzLZCYNWDc4WJEErzqZ7gFQy42eACXNBQ8m2AI7fqAQJa4YPy/HvWbdvBIL7nwnCUHka4vw6NfiA8iFvxJr09gRqk3A1j1BOpMUH5vz8TcCQgh4LmALAGA68kNgq4nFZMZjrzzi2cGKDHNM+fHsLkSFbJd9WBLXPDEXqt0X4UsNDGOZjd5Ft+5Py/CMngdaecE1q+4q1769uWaRWxxJ1BMh9bVbsQKebWEdTxlhWua6c5uJ/VqjQGGnBIX0Kl7suSIIyzwr8=
