apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acme-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    tsig-secret: AgCBDvP3AOeaPVyE+xbmZ66byDdt06ZcIDLzjiLzK/yYVv7VF7zfibz498rBRguSPEHdGlvm2nA+X00jBE/AXkxKhn57CjOzOTn0mjdsl+McYyrZq1+wPJme4mV2zs9N/VRmJc/W4iMiFGWF7dCPq5ntxUOE9MpCXNT85F19MgX4XRjserG+b2jjU/HMyCoBKdFvo1Lp9RQ/qjW5laFpYVc+GRst3kp4RcqbSzZEhVc1GPD2gOXkpskWM562+K704TWkofHsiiqsOUAS0SJf/2ERw/IGej+W8T4aGfZ/wdBVn/DW0cjgdRXTBUWQvLCJMFlt0M2QCsbsfOyLHFVQq8fcLFjDwrU1zeeSeoIkadcw/krEHQ6FoDiEu6fLZ/+ChBmVwxtBLilGpcAAbX9D9FW3Xzu5diPKMwUbHOin2/WtwstDUET/DZdiEvEkOY3ws1p1yBey9yye8NAmAm6Y8Ziblf8qtJkDA1ql1jOmWh53GCpjofMQLpebZLVsY1aENS1Canz5Y93oOX48rGizAalXSl5p4vTxqz9uISdPO8AatAMnLRZYjuRVfPQlRK4vxJd1WNsmwtUrtNrTC3ygMCW/QkX96kqpOffYHStmjPjyuYMmXo778UKj5BcdnK7J9ZmO8jbnjckW4X1JxAivpYon5dQjsBLNR9NrqYoOh+p9CeNfqHyY2GXaGaBwuVrChE0=
  template:
    metadata:
      name: acme-rfc2136-tsig
      namespace: cert-manager