apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: ssh://git@forgejo.biplane.v6.rocks:2222/artemiy/homelab.git
        revision: main
        files:
          - path: "apps/*/app.yaml"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: '{{.project}}'
      source:
        repoURL: ssh://git@forgejo.biplane.v6.rocks:2222/artemiy/homelab.git
        targetRevision: d43738ceb9816ed6863e6d4f7ad92dab2b57660f
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true