apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: zitadel-strip-api
  namespace: zitadel
spec:
  stripPrefix:
    prefixes:
      - /api
    forceSlash: false
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: zitadel-root-rewrite
  namespace: zitadel
spec:
  replacePath:
    path: /ui/v2/login/
