---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirlingpdf
  namespace: pdf
spec:
  template:
    metadata:
      name: stirlingpdf
      namespace: pdf
    type: Opaque
  encryptedData:
    PDF_ADMIN_PASSWORD: AgCL2aQxsYxz+8Rl41ZNKfckgTGcnsvQaZvzpq3VdjnxtZ/r6ElimWw0ZRvhpxsxvAnRl54Cj1b1k6KwbPJxH2unn1dqzz4WaVqflWPImr1ut/fidJF6kZAVkiXHH/qSjtVnnmeT+ucQUREeLhHd9ijPwU48yeYH+dKF/+pf8LcT1ZTKCYVjJb+/GNfz14m7iH3RXK4VujmnnLqFrMmjKbmIkgkSEnr+j/jx4/ARDwYkl6kkgiQ5Z2BVqJNwpO+1oM16OyOOiF7QXUtzp4Rwg11WoiWMqQH1wIaI0I3zdXh470K/q5ifccSvT4XO0rNTM+ih03+dUX3/cfa+VJhrjCe+HgaAgC0Y/FSXtOAM6oHKVkbBxtY9D9Kd3ud0O6TYKQePw4zMKyQ3hDrtimUem5IpZoU0ld041DSAp9s7u76OiUoSKTPAAFdYbW2b876CxNe4D08y1jTlCLLi2mLMWpOAI7XsfLaaZZvQ5jsIMvy3vFKtRE2CkzdqFzYj6ooIQZJTuAiBz1mohER9E+rbNF+gIPeiYBCUIjs0KkGLWbmTQECTAlQ113NRw5wLeMVfYCCRGFL2FuW5U8YP+QgaPxq28kKsmhEELWT/Pg3FatDmzU7+n6ZuHm2K0NKX65pRVXQbcFXypKIlYMSrW7f8taP1kmMaSCQl++/l7cEU3hIHrRVHj+ssWDojs90+ZKFpof5nDYAMd4nPYn4L7NPzXnH5Pss3ECkeeXMOdUVyou+XeW0DhA0pMBRQtHHEyKaCeVU=
    PDF_ADMIN_USERNAME: AgCQrXlt5wOcT9OulgUSVXwM5xd5SVHvY9Yyf5bfGWcH/AvzBz94nn6A4zrR7pniAHcsFQuTgIMiRo2vu8Uw9i2dRKjPlUuols37EuVjE8cjayJz+R4dFM5HMb23c3GVJCACZmdBBaXrjbWgfzqaSYmYj5SzMOqpdzMVCYXp3UsgEHcyb6xtLC98jhPwcE7SlWHKmMOgI0Es7WCWEnlEkRw5R9SwbYW8wlv5QHzPDlP/DEH2NI+HTh8mV0/ybBAZqPm1DrAwaGV5YFMH6Imaxo1KIDXQNSzcibY/XNjv5KXv9vUBwXDMMWB0CY49HD6clS1/SznlFdbOxZuMBlFY5NWLUKTPkTXwsUC3UHMcpRg0qw6Mfro7fJxkgSXmoM3MfCYV5O/Vtk9JR39aa7VdmzZF7lmBcP9Ckd86NoVbMhOFzeGYuATloFjshPWJJl4hnDCf1XBMu2KvTToeKP2krqoOYeLFCshm1yhyjAyW5dx5ygwbjCaLO9ozJQV7QcBDrWiCRT+2t1OYgpeskXwor9s9eD1Uqi45t5/4GR0ixbXRDiDBBVeKmEzccyeCKVXY7ORGC/5ny9Yqpi8UoN4QuhN0490tJPBEQ+imBgg3QE2o5aqyVa+WsrobCPtYVnduwwvtuZw/bx3AcCpgJlKMWzFMj9OlxHf/w9pDW8gYbqO0Emb4Je6McE122XJz/qXuleACocZ49A==
