---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirlingpdf
  namespace: default
spec:
  encryptedData:
    PDF_ADMIN_PASSWORD: AgB2khOKVUIeatpJC3ikiiqNlv7AyHezcaSJ5Q7zizZhEBr+xe93s0rVMuNUPNhAO9n1+kzPh+zk4MH5TDJ78nIITYoKQfuOGb1ZcFZvaChDVes1XKlhQR++J3xt60KcHJDkNQ71awiOz5Lk3wyq1Ex5rM4qIC7F2i5WOSudhhIlNtSRjtTz/HhPgkkR/C6XUEz24DWCnMDJgZ33mxF4CDUoa6yBvgRoyZOQMVGXvJaQau4DOQgRkoG23F5eoag1MXrAtC/1FQhvRebE2l8Am9tkw8ZCwWw8vP2AQhenYl/tD0aI/bj1WdRHRfq5NIDHtkKpjw1Qx22TTTaZnbxPDZrpj/10gqp8jXGPT4o3ukfPQ33A3vO9AWc0duA0iplMwkyDQEy0MO1fUDPQJi2sEmvmS8fUFXZkoKDdmYNdow2a+PGeKAWvk/KL3mMmtnyA6aSJnNRFhrVHvXuFqsj5fCch2NLD8dzmWleic9pe1C5rK5Bfzm1dOI5jq37vG9OlbNkc5gtGKsG0BEF1ciweIBdJU9JphTXjTXPTsoIQaJYHwSEHql72+D0B2AkhCuF+bCeyywjEVbPjnjGF0q+j2KyVsC5xR8+QWRZOGdcBR81yw5BvUCzOKeGS0b2jQkZIMARAtIj5uxBTSzf3PI3Tt25l8KfnLHJE97d6XiY3m7pnzyydSw0VHiNtkeFzsbpyDtRftUnwNGPGhOrI4KIeGqZ85+xNX+hYnNO/poiMKcSYnzREBXwvt9wP3EXCmRXBI1s=
    PDF_ADMIN_USERNAME: AgBOzB2eIesET0QSKdh7VJLxgjGmPmT+tKU0m14bA81i/f9y+G3D+YSrXJiXmPPlvm1edUzugV5Kf/pVqpwkDdwOrrOFCOLNWAJsCH3KLF5b5qX9uXoo7kCFoXWirHha6LS4ugTMWkQA2uUl4lUoPUNTGu93c/xHXQDXMNJkyRDLW7VJPt31XzYfJesF0jBc4Z876hV44Uz/RmDYkpAaLnCMPs4MuomxpfpOGJrEcM0vMwn11sQfqzHvYsXYEm/4VavhHD7IwsauUfseLgFkxD3EBhWzQMk9Dwf/BoPgql5laq0oT+mjVQFC2maiu6tlKLzf6AqnBJqH/5pdyuMtXI9O/Km1QHMkKVlOJgeu5sbBfVpu9e43OvhGM+15hQxVexjXW7brrrkBh8KIM1XK1WmIcq7GR8nhXkrTaAX4o1SmpIc28A9ABSkULKRWTUajpEIo022lh99NK1ng9WN70i0kh9n7v5F94zMgC1xa9iM/F1+VN/Bdb/m/CRvJEB8+YuqhUVWNISReHEmY1pK8/5SisKFVhw8fElH/b8hdF9Ap1HPUiVIjrczAJorcOXKqcKYzL6A/Dh3T/qknKrKOEApl/m8pAuVhhGgPVLhOYDbNekPql02HntL18452rXRF38kgzE0B2gYQOYNlN8JsVodAyLD/ZqPbv56myqR/87VAIus7IOqjpLIfrUssmADCTBcVbYfVDg==
  template:
    metadata:
      name: stirlingpdf
      namespace: default
