apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pdf-admin
  namespace: pdf
spec:
  vaultAuthRef: vso-pdf
  mount: kv
  type: kv-v2
  path: pdf/admin
  refreshAfter: 1h
  destination:
    name: pdf-admin
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
