apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-pdf
  namespace: pdf
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-pdf
  namespace: pdf
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: pdf
    serviceAccount: vso-pdf
