apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi
resources:
  - namespace.yaml
  - jvb.service.yaml
  - prosody.service.yaml
  - web.service.yaml
  - web.deployment.yaml
  - jicofo.deployment.yaml
  - jvb.deployment.yaml
  - prosody.deployment.yaml
  - pvcs.yaml
  - networkpolicy.yaml
  - route.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml