apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-oauth2-proxy
  namespace: oauth2-proxy
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-oauth2-proxy
  namespace: oauth2-proxy
spec:
  vaultAuthGlobalRef:
    name: vso-global
    namespace: vault-secrets-operator
  kubernetes:
    role: oauth2-proxy
    serviceAccount: vso-oauth2-proxy
