apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 3x-ui-db
  namespace: 3x-ui
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
