apiVersion: apps/v1
kind: Deployment
metadata:
  name: lute
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: lute
  template:
    metadata:
      labels:
        app: lute
    spec:
      restartPolicy: Always
      containers:
        - name: lute
          image: "jzohrab/lute3:3.10.3@sha256:ca0c26b8160a6e68d15af9a0e8de3ee2443ca1587e1cf5091cece5907b0a05d4"
          resources:
            requests:
              cpu: 1m
              memory: 256Mi
            limits:
              cpu: 50m
              memory: 512Mi
          ports:
            - containerPort: 5001
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 10
            initialDelaySeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["DAC_OVERRIDE"]
          volumeMounts:
            - name: data
              mountPath: /lute_data
            - name: backup
              mountPath: /lute_backup
      volumes:
        - name: data
          hostPath:
            path: /storage/apps/lute/data/data
        - name: backup
          hostPath:
            path: /storage/apps/lute/data/backups