---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-masterkey
  namespace: zitadel
spec:
  encryptedData:
    masterkey: AgACmGYXvVl9EiTgHGsVSPU1GJrzAHnOP8Ywb7lwlFYVSTekdxZYY8Ca5vcnH42uosqmRRvdzHeIEIMDwpwc8loMDPHEiQiD3kfz1fh9dxVYZy30GIkzeaiz6EwPfiA5SRtKM1gNBCmR22fpX1Eb9CpQF447IGfyhm/njQinY3vb/EYUTh+qAOqH6H6phzuAQEYrmuqNy3k7PFWfmoRIHWTG1kQatLCD2LFNFq5xakUGa0jVW3d3N5GRAYjfvr7xA7zeK9SEcPonldidNKld/KQIjR9vKwH2hjGez4Ov0ZCqLn6XUU3Z30xDNBYYH0DVDVDfEpP55it2A9tAUNIJsa6Ina2im55YNFOUedJM4racS5G1gfrkgn7OKDN0xBfTsxFexGn2sWekOzaKi/PjveB8d/OepHJPqtFw2p2uhylQkdfaopUrdXuLyqJ2znfFPeyiIoP+iA/f9gK0DWm9Fo655No2DPn0dFAnuktSY891IMfGLkBO1Yz3RW+3EBM3zI0dXioSzj4B12jr7afdHGnTiya9OMZ5xkJCaDpiu1l0l41w7aQHIg9NVeIzqZEiZiLnbB4MVsf4JMdbMakzF77oHJ3euBanKNI9F6obNu3ITJP0lU7OuNpb7X7xlLXFBhDaNoKqypuyef3mod4R6dJuJOc6/F8UXaFTMr3MXceLUuailT+R0fIRDdqfs7SX0gouM0sXnrgsHpBofhbjStDmQs1l6qChwreDRxBaaa7w5Q==
  template:
    metadata:
      name: zitadel-masterkey
      namespace: zitadel
    type: Opaque
