apiVersion: v1
kind: Service
metadata:
  name: zitadel
  namespace: zitadel
spec:
  type: ClusterIP
  selector:
    app: zitadel
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
